BEGIN;

ALTER TABLE eshkere.ad_campaign
    ADD COLUMN IF NOT EXISTS title      TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS short_desc TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS image_url  TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS target_url TEXT NOT NULL DEFAULT '';

COMMIT;
