// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.33.1
// source: proto/profile/v1/profile.proto

package profilev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProfileRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VisitorId     string                 `protobuf:"bytes,1,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileRequest) Reset() {
	*x = GetProfileRequest{}
	mi := &file_proto_profile_v1_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileRequest) ProtoMessage() {}

func (x *GetProfileRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_v1_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileRequest.ProtoReflect.Descriptor instead.
func (*GetProfileRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_v1_profile_proto_rawDescGZIP(), []int{0}
}

func (x *GetProfileRequest) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

type TopicScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int32                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TopicScore) Reset() {
	*x = TopicScore{}
	mi := &file_proto_profile_v1_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopicScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopicScore) ProtoMessage() {}

func (x *TopicScore) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_v1_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopicScore.ProtoReflect.Descriptor instead.
func (*TopicScore) Descriptor() ([]byte, []int) {
	return file_proto_profile_v1_profile_proto_rawDescGZIP(), []int{1}
}

func (x *TopicScore) GetTopicId() int32 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *TopicScore) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

type GetProfileResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Topics        []*TopicScore          `protobuf:"bytes,2,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfileResponse) Reset() {
	*x = GetProfileResponse{}
	mi := &file_proto_profile_v1_profile_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfileResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfileResponse) ProtoMessage() {}

func (x *GetProfileResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_v1_profile_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfileResponse.ProtoReflect.Descriptor instead.
func (*GetProfileResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_v1_profile_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfileResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *GetProfileResponse) GetTopics() []*TopicScore {
	if x != nil {
		return x.Topics
	}
	return nil
}

type TrackEventRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VisitorId     string                 `protobuf:"bytes,1,opt,name=visitor_id,json=visitorId,proto3" json:"visitor_id,omitempty"`
	TopicId       int32                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	EventType     string                 `protobuf:"bytes,3,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventRequest) Reset() {
	*x = TrackEventRequest{}
	mi := &file_proto_profile_v1_profile_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventRequest) ProtoMessage() {}

func (x *TrackEventRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_v1_profile_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventRequest.ProtoReflect.Descriptor instead.
func (*TrackEventRequest) Descriptor() ([]byte, []int) {
	return file_proto_profile_v1_profile_proto_rawDescGZIP(), []int{3}
}

func (x *TrackEventRequest) GetVisitorId() string {
	if x != nil {
		return x.VisitorId
	}
	return ""
}

func (x *TrackEventRequest) GetTopicId() int32 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *TrackEventRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

type TrackEventResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrackEventResponse) Reset() {
	*x = TrackEventResponse{}
	mi := &file_proto_profile_v1_profile_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrackEventResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrackEventResponse) ProtoMessage() {}

func (x *TrackEventResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_profile_v1_profile_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrackEventResponse.ProtoReflect.Descriptor instead.
func (*TrackEventResponse) Descriptor() ([]byte, []int) {
	return file_proto_profile_v1_profile_proto_rawDescGZIP(), []int{4}
}

var File_proto_profile_v1_profile_proto protoreflect.FileDescriptor

const file_proto_profile_v1_profile_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/profile/v1/profile.proto\x12\x12eshkere.profile.v1\"2\n" +
	"\x11GetProfileRequest\x12\x1d\n" +
	"\n" +
	"visitor_id\x18\x01 \x01(\tR\tvisitorId\"=\n" +
	"\n" +
	"TopicScore\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x05R\atopicId\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\"b\n" +
	"\x12GetProfileResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x126\n" +
	"\x06topics\x18\x02 \x03(\v2\x1e.eshkere.profile.v1.TopicScoreR\x06topics\"l\n" +
	"\x11TrackEventRequest\x12\x1d\n" +
	"\n" +
	"visitor_id\x18\x01 \x01(\tR\tvisitorId\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x05R\atopicId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x03 \x01(\tR\teventType\"\x14\n" +
	"\x12TrackEventResponse2\xca\x01\n" +
	"\x0eProfileService\x12[\n" +
	"\n" +
	"GetProfile\x12%.eshkere.profile.v1.GetProfileRequest\x1a&.eshkere.profile.v1.GetProfileResponse\x12[\n" +
	"\n" +
	"TrackEvent\x12%.eshkere.profile.v1.TrackEventRequest\x1a&.eshkere.profile.v1.TrackEventResponseB%Z#eshkere/pkg/pb/profile/v1;profilev1b\x06proto3"

var (
	file_proto_profile_v1_profile_proto_rawDescOnce sync.Once
	file_proto_profile_v1_profile_proto_rawDescData []byte
)

func file_proto_profile_v1_profile_proto_rawDescGZIP() []byte {
	file_proto_profile_v1_profile_proto_rawDescOnce.Do(func() {
		file_proto_profile_v1_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_profile_v1_profile_proto_rawDesc), len(file_proto_profile_v1_profile_proto_rawDesc)))
	})
	return file_proto_profile_v1_profile_proto_rawDescData
}

var file_proto_profile_v1_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_profile_v1_profile_proto_goTypes = []any{
	(*GetProfileRequest)(nil),  // 0: eshkere.profile.v1.GetProfileRequest
	(*TopicScore)(nil),         // 1: eshkere.profile.v1.TopicScore
	(*GetProfileResponse)(nil), // 2: eshkere.profile.v1.GetProfileResponse
	(*TrackEventRequest)(nil),  // 3: eshkere.profile.v1.TrackEventRequest
	(*TrackEventResponse)(nil), // 4: eshkere.profile.v1.TrackEventResponse
}
var file_proto_profile_v1_profile_proto_depIdxs = []int32{
	1, // 0: eshkere.profile.v1.GetProfileResponse.topics:type_name -> eshkere.profile.v1.TopicScore
	0, // 1: eshkere.profile.v1.ProfileService.GetProfile:input_type -> eshkere.profile.v1.GetProfileRequest
	3, // 2: eshkere.profile.v1.ProfileService.TrackEvent:input_type -> eshkere.profile.v1.TrackEventRequest
	2, // 3: eshkere.profile.v1.ProfileService.GetProfile:output_type -> eshkere.profile.v1.GetProfileResponse
	4, // 4: eshkere.profile.v1.ProfileService.TrackEvent:output_type -> eshkere.profile.v1.TrackEventResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_profile_v1_profile_proto_init() }
func file_proto_profile_v1_profile_proto_init() {
	if File_proto_profile_v1_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_profile_v1_profile_proto_rawDesc), len(file_proto_profile_v1_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_profile_v1_profile_proto_goTypes,
		DependencyIndexes: file_proto_profile_v1_profile_proto_depIdxs,
		MessageInfos:      file_proto_profile_v1_profile_proto_msgTypes,
	}.Build()
	File_proto_profile_v1_profile_proto = out.File
	file_proto_profile_v1_profile_proto_goTypes = nil
	file_proto_profile_v1_profile_proto_depIdxs = nil
}
