http_server:
  listen: ":8000"
  read_timeout: 15s
  write_timeout: 15s

postgres:
  host: ${POSTGRES_HOST}
  port: 5432
  database: ${POSTGRES_DB}
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}

graceful_timeout: 20s

redis:
  host: ${REDIS_HOST}
  port: 6379
  password: ${REDIS_PASSWORD}
  db: 0
  max_idle: 4
  max_active: 16
  idle_timeout: 5m
  wait: true
  connect_timeout: 5s
  read_timeout: 5s
  write_timeout: 5s
  ping_after_idle_for: 1m

session:
  ttl: 24h
  cookie_name: "session_id"
  cookie_path: "/"
  cookie_secure: false

s3:
  endpoint: ${S3_ENDPOINT}
  region: ${S3_REGION}
  bucket: ${S3_BUCKET}
  access_key: ${S3_ACCESS_KEY}
  secret_key: ${S3_SECRET_KEY}
  public_base_url: ${S3_PUBLIC_BASE_URL}
  # для MinIO / кастомного endpoint обычно true; для нативного AWS S3 — false
  force_path_style: true

admin:
  token: ${ADMIN_TOKEN}

cors:
  allowed_origins:
    - "http://localhost:8080"
    - "http://127.0.0.1:8080"
    - "http://212.233.96.112:8080"
