// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/service.go -destination=internal/service/repo_mocks_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	models "eshkere/internal/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockAdvertiserRepository is a mock of AdvertiserRepository interface.
type MockAdvertiserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdvertiserRepositoryMockRecorder
	isgomock struct{}
}

// MockAdvertiserRepositoryMockRecorder is the mock recorder for MockAdvertiserRepository.
type MockAdvertiserRepositoryMockRecorder struct {
	mock *MockAdvertiserRepository
}

// NewMockAdvertiserRepository creates a new mock instance.
func NewMockAdvertiserRepository(ctrl *gomock.Controller) *MockAdvertiserRepository {
	mock := &MockAdvertiserRepository{ctrl: ctrl}
	mock.recorder = &MockAdvertiserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdvertiserRepository) EXPECT() *MockAdvertiserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdvertiserRepository) Create(ctx context.Context, a *models.Advertiser) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, a)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAdvertiserRepositoryMockRecorder) Create(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdvertiserRepository)(nil).Create), ctx, a)
}

// GetByEmail mocks base method.
func (m *MockAdvertiserRepository) GetByEmail(ctx context.Context, email string) (*models.Advertiser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmail", ctx, email)
	ret0, _ := ret[0].(*models.Advertiser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmail indicates an expected call of GetByEmail.
func (mr *MockAdvertiserRepositoryMockRecorder) GetByEmail(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmail", reflect.TypeOf((*MockAdvertiserRepository)(nil).GetByEmail), ctx, email)
}

// GetByID mocks base method.
func (m *MockAdvertiserRepository) GetByID(ctx context.Context, id int) (*models.Advertiser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Advertiser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAdvertiserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAdvertiserRepository)(nil).GetByID), ctx, id)
}

// GetByPhone mocks base method.
func (m *MockAdvertiserRepository) GetByPhone(ctx context.Context, phone string) (*models.Advertiser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPhone", ctx, phone)
	ret0, _ := ret[0].(*models.Advertiser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPhone indicates an expected call of GetByPhone.
func (mr *MockAdvertiserRepositoryMockRecorder) GetByPhone(ctx, phone any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPhone", reflect.TypeOf((*MockAdvertiserRepository)(nil).GetByPhone), ctx, phone)
}

// Update mocks base method.
func (m *MockAdvertiserRepository) Update(ctx context.Context, a *models.Advertiser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdvertiserRepositoryMockRecorder) Update(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdvertiserRepository)(nil).Update), ctx, a)
}

// MockPartnerRepository is a mock of PartnerRepository interface.
type MockPartnerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPartnerRepositoryMockRecorder
	isgomock struct{}
}

// MockPartnerRepositoryMockRecorder is the mock recorder for MockPartnerRepository.
type MockPartnerRepositoryMockRecorder struct {
	mock *MockPartnerRepository
}

// NewMockPartnerRepository creates a new mock instance.
func NewMockPartnerRepository(ctrl *gomock.Controller) *MockPartnerRepository {
	mock := &MockPartnerRepository{ctrl: ctrl}
	mock.recorder = &MockPartnerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartnerRepository) EXPECT() *MockPartnerRepositoryMockRecorder {
	return m.recorder
}

// MockPartnerSiteRepository is a mock of PartnerSiteRepository interface.
type MockPartnerSiteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPartnerSiteRepositoryMockRecorder
	isgomock struct{}
}

// MockPartnerSiteRepositoryMockRecorder is the mock recorder for MockPartnerSiteRepository.
type MockPartnerSiteRepositoryMockRecorder struct {
	mock *MockPartnerSiteRepository
}

// NewMockPartnerSiteRepository creates a new mock instance.
func NewMockPartnerSiteRepository(ctrl *gomock.Controller) *MockPartnerSiteRepository {
	mock := &MockPartnerSiteRepository{ctrl: ctrl}
	mock.recorder = &MockPartnerSiteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartnerSiteRepository) EXPECT() *MockPartnerSiteRepositoryMockRecorder {
	return m.recorder
}

// MockAdCampaignRepository is a mock of AdCampaignRepository interface.
type MockAdCampaignRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdCampaignRepositoryMockRecorder
	isgomock struct{}
}

// MockAdCampaignRepositoryMockRecorder is the mock recorder for MockAdCampaignRepository.
type MockAdCampaignRepositoryMockRecorder struct {
	mock *MockAdCampaignRepository
}

// NewMockAdCampaignRepository creates a new mock instance.
func NewMockAdCampaignRepository(ctrl *gomock.Controller) *MockAdCampaignRepository {
	mock := &MockAdCampaignRepository{ctrl: ctrl}
	mock.recorder = &MockAdCampaignRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdCampaignRepository) EXPECT() *MockAdCampaignRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdCampaignRepository) Create(ctx context.Context, c *models.AdCampaign) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAdCampaignRepositoryMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdCampaignRepository)(nil).Create), ctx, c)
}

// Delete mocks base method.
func (m *MockAdCampaignRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdCampaignRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdCampaignRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockAdCampaignRepository) GetByID(ctx context.Context, id int) (*models.AdCampaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.AdCampaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAdCampaignRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAdCampaignRepository)(nil).GetByID), ctx, id)
}

// ListByAdvertiserID mocks base method.
func (m *MockAdCampaignRepository) ListByAdvertiserID(ctx context.Context, advertiserID int) ([]*models.AdCampaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAdvertiserID", ctx, advertiserID)
	ret0, _ := ret[0].([]*models.AdCampaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAdvertiserID indicates an expected call of ListByAdvertiserID.
func (mr *MockAdCampaignRepositoryMockRecorder) ListByAdvertiserID(ctx, advertiserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAdvertiserID", reflect.TypeOf((*MockAdCampaignRepository)(nil).ListByAdvertiserID), ctx, advertiserID)
}

// Update mocks base method.
func (m *MockAdCampaignRepository) Update(ctx context.Context, c *models.AdCampaign) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdCampaignRepositoryMockRecorder) Update(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdCampaignRepository)(nil).Update), ctx, c)
}

// MockAdGroupRepository is a mock of AdGroupRepository interface.
type MockAdGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockAdGroupRepositoryMockRecorder is the mock recorder for MockAdGroupRepository.
type MockAdGroupRepositoryMockRecorder struct {
	mock *MockAdGroupRepository
}

// NewMockAdGroupRepository creates a new mock instance.
func NewMockAdGroupRepository(ctrl *gomock.Controller) *MockAdGroupRepository {
	mock := &MockAdGroupRepository{ctrl: ctrl}
	mock.recorder = &MockAdGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdGroupRepository) EXPECT() *MockAdGroupRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdGroupRepository) Create(ctx context.Context, g *models.AdGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAdGroupRepositoryMockRecorder) Create(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdGroupRepository)(nil).Create), ctx, g)
}

// Delete mocks base method.
func (m *MockAdGroupRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdGroupRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdGroupRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockAdGroupRepository) GetByID(ctx context.Context, id int) (*models.AdGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.AdGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAdGroupRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAdGroupRepository)(nil).GetByID), ctx, id)
}

// ListByCampaignID mocks base method.
func (m *MockAdGroupRepository) ListByCampaignID(ctx context.Context, campaignID int) ([]*models.AdGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCampaignID", ctx, campaignID)
	ret0, _ := ret[0].([]*models.AdGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCampaignID indicates an expected call of ListByCampaignID.
func (mr *MockAdGroupRepositoryMockRecorder) ListByCampaignID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCampaignID", reflect.TypeOf((*MockAdGroupRepository)(nil).ListByCampaignID), ctx, campaignID)
}

// Update mocks base method.
func (m *MockAdGroupRepository) Update(ctx context.Context, g *models.AdGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdGroupRepositoryMockRecorder) Update(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdGroupRepository)(nil).Update), ctx, g)
}

// MockAdRepository is a mock of AdRepository interface.
type MockAdRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdRepositoryMockRecorder
	isgomock struct{}
}

// MockAdRepositoryMockRecorder is the mock recorder for MockAdRepository.
type MockAdRepositoryMockRecorder struct {
	mock *MockAdRepository
}

// NewMockAdRepository creates a new mock instance.
func NewMockAdRepository(ctrl *gomock.Controller) *MockAdRepository {
	mock := &MockAdRepository{ctrl: ctrl}
	mock.recorder = &MockAdRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdRepository) EXPECT() *MockAdRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdRepository) Create(ctx context.Context, ad *models.Ad) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ad)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAdRepositoryMockRecorder) Create(ctx, ad any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdRepository)(nil).Create), ctx, ad)
}

// Delete mocks base method.
func (m *MockAdRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockAdRepository) GetByID(ctx context.Context, adID int) (*models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, adID)
	ret0, _ := ret[0].(*models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAdRepositoryMockRecorder) GetByID(ctx, adID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAdRepository)(nil).GetByID), ctx, adID)
}

// ListByAdGroupID mocks base method.
func (m *MockAdRepository) ListByAdGroupID(ctx context.Context, adGroupID int) ([]*models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAdGroupID", ctx, adGroupID)
	ret0, _ := ret[0].([]*models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAdGroupID indicates an expected call of ListByAdGroupID.
func (mr *MockAdRepositoryMockRecorder) ListByAdGroupID(ctx, adGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAdGroupID", reflect.TypeOf((*MockAdRepository)(nil).ListByAdGroupID), ctx, adGroupID)
}

// ListByAdvertiserID mocks base method.
func (m *MockAdRepository) ListByAdvertiserID(ctx context.Context, advertiserID int) ([]*models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAdvertiserID", ctx, advertiserID)
	ret0, _ := ret[0].([]*models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAdvertiserID indicates an expected call of ListByAdvertiserID.
func (mr *MockAdRepositoryMockRecorder) ListByAdvertiserID(ctx, advertiserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAdvertiserID", reflect.TypeOf((*MockAdRepository)(nil).ListByAdvertiserID), ctx, advertiserID)
}

// Update mocks base method.
func (m *MockAdRepository) Update(ctx context.Context, ad *models.Ad) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, ad)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdRepositoryMockRecorder) Update(ctx, ad any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdRepository)(nil).Update), ctx, ad)
}

// MockFeedLinkRepository is a mock of FeedLinkRepository interface.
type MockFeedLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedLinkRepositoryMockRecorder
	isgomock struct{}
}

// MockFeedLinkRepositoryMockRecorder is the mock recorder for MockFeedLinkRepository.
type MockFeedLinkRepositoryMockRecorder struct {
	mock *MockFeedLinkRepository
}

// NewMockFeedLinkRepository creates a new mock instance.
func NewMockFeedLinkRepository(ctrl *gomock.Controller) *MockFeedLinkRepository {
	mock := &MockFeedLinkRepository{ctrl: ctrl}
	mock.recorder = &MockFeedLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedLinkRepository) EXPECT() *MockFeedLinkRepositoryMockRecorder {
	return m.recorder
}

// GetAdvertiserIDByToken mocks base method.
func (m *MockFeedLinkRepository) GetAdvertiserIDByToken(ctx context.Context, token string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdvertiserIDByToken", ctx, token)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdvertiserIDByToken indicates an expected call of GetAdvertiserIDByToken.
func (mr *MockFeedLinkRepositoryMockRecorder) GetAdvertiserIDByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdvertiserIDByToken", reflect.TypeOf((*MockFeedLinkRepository)(nil).GetAdvertiserIDByToken), ctx, token)
}

// UpsertByAdvertiserID mocks base method.
func (m *MockFeedLinkRepository) UpsertByAdvertiserID(ctx context.Context, advertiserID int, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertByAdvertiserID", ctx, advertiserID, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertByAdvertiserID indicates an expected call of UpsertByAdvertiserID.
func (mr *MockFeedLinkRepositoryMockRecorder) UpsertByAdvertiserID(ctx, advertiserID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertByAdvertiserID", reflect.TypeOf((*MockFeedLinkRepository)(nil).UpsertByAdvertiserID), ctx, advertiserID, token)
}

// MockAvatarStorage is a mock of AvatarStorage interface.
type MockAvatarStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarStorageMockRecorder
	isgomock struct{}
}

// MockAvatarStorageMockRecorder is the mock recorder for MockAvatarStorage.
type MockAvatarStorageMockRecorder struct {
	mock *MockAvatarStorage
}

// NewMockAvatarStorage creates a new mock instance.
func NewMockAvatarStorage(ctrl *gomock.Controller) *MockAvatarStorage {
	mock := &MockAvatarStorage{ctrl: ctrl}
	mock.recorder = &MockAvatarStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarStorage) EXPECT() *MockAvatarStorageMockRecorder {
	return m.recorder
}

// UploadAvatar mocks base method.
func (m *MockAvatarStorage) UploadAvatar(ctx context.Context, advertiserID int, data []byte, filename, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", ctx, advertiserID, data, filename, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockAvatarStorageMockRecorder) UploadAvatar(ctx, advertiserID, data, filename, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockAvatarStorage)(nil).UploadAvatar), ctx, advertiserID, data, filename, contentType)
}

// MockAdActionRepository is a mock of AdActionRepository interface.
type MockAdActionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdActionRepositoryMockRecorder
	isgomock struct{}
}

// MockAdActionRepositoryMockRecorder is the mock recorder for MockAdActionRepository.
type MockAdActionRepositoryMockRecorder struct {
	mock *MockAdActionRepository
}

// NewMockAdActionRepository creates a new mock instance.
func NewMockAdActionRepository(ctrl *gomock.Controller) *MockAdActionRepository {
	mock := &MockAdActionRepository{ctrl: ctrl}
	mock.recorder = &MockAdActionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdActionRepository) EXPECT() *MockAdActionRepositoryMockRecorder {
	return m.recorder
}

// MockTopicRepository is a mock of TopicRepository interface.
type MockTopicRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTopicRepositoryMockRecorder
	isgomock struct{}
}

// MockTopicRepositoryMockRecorder is the mock recorder for MockTopicRepository.
type MockTopicRepositoryMockRecorder struct {
	mock *MockTopicRepository
}

// NewMockTopicRepository creates a new mock instance.
func NewMockTopicRepository(ctrl *gomock.Controller) *MockTopicRepository {
	mock := &MockTopicRepository{ctrl: ctrl}
	mock.recorder = &MockTopicRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopicRepository) EXPECT() *MockTopicRepositoryMockRecorder {
	return m.recorder
}

// MockRegionRepository is a mock of RegionRepository interface.
type MockRegionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRegionRepositoryMockRecorder
	isgomock struct{}
}

// MockRegionRepositoryMockRecorder is the mock recorder for MockRegionRepository.
type MockRegionRepositoryMockRecorder struct {
	mock *MockRegionRepository
}

// NewMockRegionRepository creates a new mock instance.
func NewMockRegionRepository(ctrl *gomock.Controller) *MockRegionRepository {
	mock := &MockRegionRepository{ctrl: ctrl}
	mock.recorder = &MockRegionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegionRepository) EXPECT() *MockRegionRepositoryMockRecorder {
	return m.recorder
}
