// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go
//
// Generated by this command:
//
//	mockgen -source=internal/service/service.go -destination=internal/service/repo_mocks_test.go -package=service
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	models "eshkere/internal/models"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockAdvertiserRepository is a mock of AdvertiserRepository interface.
type MockAdvertiserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdvertiserRepositoryMockRecorder
	isgomock struct{}
}

// MockAdvertiserRepositoryMockRecorder is the mock recorder for MockAdvertiserRepository.
type MockAdvertiserRepositoryMockRecorder struct {
	mock *MockAdvertiserRepository
}

// NewMockAdvertiserRepository creates a new mock instance.
func NewMockAdvertiserRepository(ctrl *gomock.Controller) *MockAdvertiserRepository {
	mock := &MockAdvertiserRepository{ctrl: ctrl}
	mock.recorder = &MockAdvertiserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdvertiserRepository) EXPECT() *MockAdvertiserRepositoryMockRecorder {
	return m.recorder
}

// CreateProfile mocks base method.
func (m *MockAdvertiserRepository) CreateProfile(ctx context.Context, id int64, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", ctx, id, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockAdvertiserRepositoryMockRecorder) CreateProfile(ctx, id, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockAdvertiserRepository)(nil).CreateProfile), ctx, id, name)
}

// GetByID mocks base method.
func (m *MockAdvertiserRepository) GetByID(ctx context.Context, id int) (*models.Advertiser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Advertiser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAdvertiserRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAdvertiserRepository)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockAdvertiserRepository) Update(ctx context.Context, a *models.Advertiser) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, a)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdvertiserRepositoryMockRecorder) Update(ctx, a any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdvertiserRepository)(nil).Update), ctx, a)
}

// ListExpiredProAdvertiserIDs mocks base method.
func (m *MockAdvertiserRepository) ListExpiredProAdvertiserIDs(ctx context.Context) ([]int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiredProAdvertiserIDs", ctx)
	ret0, _ := ret[0].([]int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiredProAdvertiserIDs indicates an expected call of ListExpiredProAdvertiserIDs.
func (mr *MockAdvertiserRepositoryMockRecorder) ListExpiredProAdvertiserIDs(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiredProAdvertiserIDs", reflect.TypeOf((*MockAdvertiserRepository)(nil).ListExpiredProAdvertiserIDs), ctx)
}

// MockPartnerRepository is a mock of PartnerRepository interface.
type MockPartnerRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPartnerRepositoryMockRecorder
	isgomock struct{}
}

// MockPartnerRepositoryMockRecorder is the mock recorder for MockPartnerRepository.
type MockPartnerRepositoryMockRecorder struct {
	mock *MockPartnerRepository
}

// NewMockPartnerRepository creates a new mock instance.
func NewMockPartnerRepository(ctrl *gomock.Controller) *MockPartnerRepository {
	mock := &MockPartnerRepository{ctrl: ctrl}
	mock.recorder = &MockPartnerRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartnerRepository) EXPECT() *MockPartnerRepositoryMockRecorder {
	return m.recorder
}

// CreateProfile mocks base method.
func (m *MockPartnerRepository) CreateProfile(ctx context.Context, partner *models.Partner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProfile", ctx, partner)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateProfile indicates an expected call of CreateProfile.
func (mr *MockPartnerRepositoryMockRecorder) CreateProfile(ctx, partner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProfile", reflect.TypeOf((*MockPartnerRepository)(nil).CreateProfile), ctx, partner)
}

// GetByID mocks base method.
func (m *MockPartnerRepository) GetByID(ctx context.Context, id int) (*models.Partner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.Partner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPartnerRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPartnerRepository)(nil).GetByID), ctx, id)
}

// SettleDailyEarnings mocks base method.
func (m *MockPartnerRepository) SettleDailyEarnings(ctx context.Context, earningDate time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SettleDailyEarnings", ctx, earningDate)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SettleDailyEarnings indicates an expected call of SettleDailyEarnings.
func (mr *MockPartnerRepositoryMockRecorder) SettleDailyEarnings(ctx, earningDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SettleDailyEarnings", reflect.TypeOf((*MockPartnerRepository)(nil).SettleDailyEarnings), ctx, earningDate)
}

// Update mocks base method.
func (m *MockPartnerRepository) Update(ctx context.Context, partner *models.Partner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, partner)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPartnerRepositoryMockRecorder) Update(ctx, partner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPartnerRepository)(nil).Update), ctx, partner)
}

// MockPartnerSiteRepository is a mock of PartnerSiteRepository interface.
type MockPartnerSiteRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPartnerSiteRepositoryMockRecorder
	isgomock struct{}
}

// MockPartnerSiteRepositoryMockRecorder is the mock recorder for MockPartnerSiteRepository.
type MockPartnerSiteRepositoryMockRecorder struct {
	mock *MockPartnerSiteRepository
}

// NewMockPartnerSiteRepository creates a new mock instance.
func NewMockPartnerSiteRepository(ctrl *gomock.Controller) *MockPartnerSiteRepository {
	mock := &MockPartnerSiteRepository{ctrl: ctrl}
	mock.recorder = &MockPartnerSiteRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartnerSiteRepository) EXPECT() *MockPartnerSiteRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPartnerSiteRepository) Create(ctx context.Context, site *models.PartnerSite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, site)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPartnerSiteRepositoryMockRecorder) Create(ctx, site any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPartnerSiteRepository)(nil).Create), ctx, site)
}

// Delete mocks base method.
func (m *MockPartnerSiteRepository) Delete(ctx context.Context, siteID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, siteID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPartnerSiteRepositoryMockRecorder) Delete(ctx, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPartnerSiteRepository)(nil).Delete), ctx, siteID)
}

// ExistsByDomain mocks base method.
func (m *MockPartnerSiteRepository) ExistsByDomain(ctx context.Context, domain string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExistsByDomain", ctx, domain)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExistsByDomain indicates an expected call of ExistsByDomain.
func (mr *MockPartnerSiteRepositoryMockRecorder) ExistsByDomain(ctx, domain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExistsByDomain", reflect.TypeOf((*MockPartnerSiteRepository)(nil).ExistsByDomain), ctx, domain)
}

// GetByID mocks base method.
func (m *MockPartnerSiteRepository) GetByID(ctx context.Context, siteID int) (*models.PartnerSite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, siteID)
	ret0, _ := ret[0].(*models.PartnerSite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPartnerSiteRepositoryMockRecorder) GetByID(ctx, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPartnerSiteRepository)(nil).GetByID), ctx, siteID)
}

// ListByPartnerID mocks base method.
func (m *MockPartnerSiteRepository) ListByPartnerID(ctx context.Context, partnerID int) ([]*models.PartnerSite, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByPartnerID", ctx, partnerID)
	ret0, _ := ret[0].([]*models.PartnerSite)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByPartnerID indicates an expected call of ListByPartnerID.
func (mr *MockPartnerSiteRepositoryMockRecorder) ListByPartnerID(ctx, partnerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByPartnerID", reflect.TypeOf((*MockPartnerSiteRepository)(nil).ListByPartnerID), ctx, partnerID)
}

// Update mocks base method.
func (m *MockPartnerSiteRepository) Update(ctx context.Context, site *models.PartnerSite) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, site)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPartnerSiteRepositoryMockRecorder) Update(ctx, site any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPartnerSiteRepository)(nil).Update), ctx, site)
}

// MockPartnerBlockRepository is a mock of PartnerBlockRepository interface.
type MockPartnerBlockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPartnerBlockRepositoryMockRecorder
	isgomock struct{}
}

// MockPartnerBlockRepositoryMockRecorder is the mock recorder for MockPartnerBlockRepository.
type MockPartnerBlockRepositoryMockRecorder struct {
	mock *MockPartnerBlockRepository
}

// NewMockPartnerBlockRepository creates a new mock instance.
func NewMockPartnerBlockRepository(ctrl *gomock.Controller) *MockPartnerBlockRepository {
	mock := &MockPartnerBlockRepository{ctrl: ctrl}
	mock.recorder = &MockPartnerBlockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartnerBlockRepository) EXPECT() *MockPartnerBlockRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPartnerBlockRepository) Create(ctx context.Context, block *models.PartnerBlock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, block)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPartnerBlockRepositoryMockRecorder) Create(ctx, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPartnerBlockRepository)(nil).Create), ctx, block)
}

// Delete mocks base method.
func (m *MockPartnerBlockRepository) Delete(ctx context.Context, blockID int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, blockID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPartnerBlockRepositoryMockRecorder) Delete(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPartnerBlockRepository)(nil).Delete), ctx, blockID)
}

// GetByEmbedToken mocks base method.
func (m *MockPartnerBlockRepository) GetByEmbedToken(ctx context.Context, token string) (*models.PartnerBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByEmbedToken", ctx, token)
	ret0, _ := ret[0].(*models.PartnerBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByEmbedToken indicates an expected call of GetByEmbedToken.
func (mr *MockPartnerBlockRepositoryMockRecorder) GetByEmbedToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByEmbedToken", reflect.TypeOf((*MockPartnerBlockRepository)(nil).GetByEmbedToken), ctx, token)
}

// GetByID mocks base method.
func (m *MockPartnerBlockRepository) GetByID(ctx context.Context, blockID int) (*models.PartnerBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, blockID)
	ret0, _ := ret[0].(*models.PartnerBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockPartnerBlockRepositoryMockRecorder) GetByID(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPartnerBlockRepository)(nil).GetByID), ctx, blockID)
}

// ListBySiteID mocks base method.
func (m *MockPartnerBlockRepository) ListBySiteID(ctx context.Context, siteID int) ([]*models.PartnerBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBySiteID", ctx, siteID)
	ret0, _ := ret[0].([]*models.PartnerBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBySiteID indicates an expected call of ListBySiteID.
func (mr *MockPartnerBlockRepositoryMockRecorder) ListBySiteID(ctx, siteID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBySiteID", reflect.TypeOf((*MockPartnerBlockRepository)(nil).ListBySiteID), ctx, siteID)
}

// Update mocks base method.
func (m *MockPartnerBlockRepository) Update(ctx context.Context, block *models.PartnerBlock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, block)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockPartnerBlockRepositoryMockRecorder) Update(ctx, block any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPartnerBlockRepository)(nil).Update), ctx, block)
}

// MockPartnerBlockGeoRuleRepository is a mock of PartnerBlockGeoRuleRepository interface.
type MockPartnerBlockGeoRuleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPartnerBlockGeoRuleRepositoryMockRecorder
	isgomock struct{}
}

// MockPartnerBlockGeoRuleRepositoryMockRecorder is the mock recorder for MockPartnerBlockGeoRuleRepository.
type MockPartnerBlockGeoRuleRepositoryMockRecorder struct {
	mock *MockPartnerBlockGeoRuleRepository
}

// NewMockPartnerBlockGeoRuleRepository creates a new mock instance.
func NewMockPartnerBlockGeoRuleRepository(ctrl *gomock.Controller) *MockPartnerBlockGeoRuleRepository {
	mock := &MockPartnerBlockGeoRuleRepository{ctrl: ctrl}
	mock.recorder = &MockPartnerBlockGeoRuleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPartnerBlockGeoRuleRepository) EXPECT() *MockPartnerBlockGeoRuleRepositoryMockRecorder {
	return m.recorder
}

// ListByBlockID mocks base method.
func (m *MockPartnerBlockGeoRuleRepository) ListByBlockID(ctx context.Context, blockID int) ([]*models.PartnerBlockGeoRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByBlockID", ctx, blockID)
	ret0, _ := ret[0].([]*models.PartnerBlockGeoRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByBlockID indicates an expected call of ListByBlockID.
func (mr *MockPartnerBlockGeoRuleRepositoryMockRecorder) ListByBlockID(ctx, blockID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByBlockID", reflect.TypeOf((*MockPartnerBlockGeoRuleRepository)(nil).ListByBlockID), ctx, blockID)
}

// ReplaceByBlockID mocks base method.
func (m *MockPartnerBlockGeoRuleRepository) ReplaceByBlockID(ctx context.Context, blockID int, rules []*models.PartnerBlockGeoRule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceByBlockID", ctx, blockID, rules)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReplaceByBlockID indicates an expected call of ReplaceByBlockID.
func (mr *MockPartnerBlockGeoRuleRepositoryMockRecorder) ReplaceByBlockID(ctx, blockID, rules any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceByBlockID", reflect.TypeOf((*MockPartnerBlockGeoRuleRepository)(nil).ReplaceByBlockID), ctx, blockID, rules)
}

// MockAdCampaignRepository is a mock of AdCampaignRepository interface.
type MockAdCampaignRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdCampaignRepositoryMockRecorder
	isgomock struct{}
}

// MockAdCampaignRepositoryMockRecorder is the mock recorder for MockAdCampaignRepository.
type MockAdCampaignRepositoryMockRecorder struct {
	mock *MockAdCampaignRepository
}

// NewMockAdCampaignRepository creates a new mock instance.
func NewMockAdCampaignRepository(ctrl *gomock.Controller) *MockAdCampaignRepository {
	mock := &MockAdCampaignRepository{ctrl: ctrl}
	mock.recorder = &MockAdCampaignRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdCampaignRepository) EXPECT() *MockAdCampaignRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdCampaignRepository) Create(ctx context.Context, c *models.AdCampaign) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAdCampaignRepositoryMockRecorder) Create(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdCampaignRepository)(nil).Create), ctx, c)
}

// Delete mocks base method.
func (m *MockAdCampaignRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdCampaignRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdCampaignRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockAdCampaignRepository) GetByID(ctx context.Context, id int) (*models.AdCampaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.AdCampaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAdCampaignRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAdCampaignRepository)(nil).GetByID), ctx, id)
}

// ListByAdvertiserID mocks base method.
func (m *MockAdCampaignRepository) ListByAdvertiserID(ctx context.Context, advertiserID int) ([]*models.AdCampaign, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAdvertiserID", ctx, advertiserID)
	ret0, _ := ret[0].([]*models.AdCampaign)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAdvertiserID indicates an expected call of ListByAdvertiserID.
func (mr *MockAdCampaignRepositoryMockRecorder) ListByAdvertiserID(ctx, advertiserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAdvertiserID", reflect.TypeOf((*MockAdCampaignRepository)(nil).ListByAdvertiserID), ctx, advertiserID)
}

// Update mocks base method.
func (m *MockAdCampaignRepository) Update(ctx context.Context, c *models.AdCampaign) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdCampaignRepositoryMockRecorder) Update(ctx, c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdCampaignRepository)(nil).Update), ctx, c)
}

// CountActiveByAdvertiserID mocks base method.
func (m *MockAdCampaignRepository) CountActiveByAdvertiserID(ctx context.Context, advertiserID int) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountActiveByAdvertiserID", ctx, advertiserID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountActiveByAdvertiserID indicates an expected call of CountActiveByAdvertiserID.
func (mr *MockAdCampaignRepositoryMockRecorder) CountActiveByAdvertiserID(ctx, advertiserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountActiveByAdvertiserID", reflect.TypeOf((*MockAdCampaignRepository)(nil).CountActiveByAdvertiserID), ctx, advertiserID)
}

// MockAdGroupRepository is a mock of AdGroupRepository interface.
type MockAdGroupRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdGroupRepositoryMockRecorder
	isgomock struct{}
}

// MockAdGroupRepositoryMockRecorder is the mock recorder for MockAdGroupRepository.
type MockAdGroupRepositoryMockRecorder struct {
	mock *MockAdGroupRepository
}

// NewMockAdGroupRepository creates a new mock instance.
func NewMockAdGroupRepository(ctrl *gomock.Controller) *MockAdGroupRepository {
	mock := &MockAdGroupRepository{ctrl: ctrl}
	mock.recorder = &MockAdGroupRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdGroupRepository) EXPECT() *MockAdGroupRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdGroupRepository) Create(ctx context.Context, g *models.AdGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAdGroupRepositoryMockRecorder) Create(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdGroupRepository)(nil).Create), ctx, g)
}

// Delete mocks base method.
func (m *MockAdGroupRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdGroupRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdGroupRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockAdGroupRepository) GetByID(ctx context.Context, id int) (*models.AdGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*models.AdGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAdGroupRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAdGroupRepository)(nil).GetByID), ctx, id)
}

// ListByCampaignID mocks base method.
func (m *MockAdGroupRepository) ListByCampaignID(ctx context.Context, campaignID int) ([]*models.AdGroup, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByCampaignID", ctx, campaignID)
	ret0, _ := ret[0].([]*models.AdGroup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByCampaignID indicates an expected call of ListByCampaignID.
func (mr *MockAdGroupRepositoryMockRecorder) ListByCampaignID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByCampaignID", reflect.TypeOf((*MockAdGroupRepository)(nil).ListByCampaignID), ctx, campaignID)
}

// Update mocks base method.
func (m *MockAdGroupRepository) Update(ctx context.Context, g *models.AdGroup) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, g)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdGroupRepositoryMockRecorder) Update(ctx, g any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdGroupRepository)(nil).Update), ctx, g)
}

// MockAdRepository is a mock of AdRepository interface.
type MockAdRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdRepositoryMockRecorder
	isgomock struct{}
}

// MockAdRepositoryMockRecorder is the mock recorder for MockAdRepository.
type MockAdRepositoryMockRecorder struct {
	mock *MockAdRepository
}

// NewMockAdRepository creates a new mock instance.
func NewMockAdRepository(ctrl *gomock.Controller) *MockAdRepository {
	mock := &MockAdRepository{ctrl: ctrl}
	mock.recorder = &MockAdRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdRepository) EXPECT() *MockAdRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdRepository) Create(ctx context.Context, ad *models.Ad) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, ad)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAdRepositoryMockRecorder) Create(ctx, ad any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdRepository)(nil).Create), ctx, ad)
}

// Delete mocks base method.
func (m *MockAdRepository) Delete(ctx context.Context, id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAdRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAdRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockAdRepository) GetByID(ctx context.Context, adID int) (*models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, adID)
	ret0, _ := ret[0].(*models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAdRepositoryMockRecorder) GetByID(ctx, adID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAdRepository)(nil).GetByID), ctx, adID)
}

// GetRandomWorking mocks base method.
func (m *MockAdRepository) GetRandomWorking(ctx context.Context) (*models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandomWorking", ctx)
	ret0, _ := ret[0].(*models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandomWorking indicates an expected call of GetRandomWorking.
func (mr *MockAdRepositoryMockRecorder) GetRandomWorking(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandomWorking", reflect.TypeOf((*MockAdRepository)(nil).GetRandomWorking), ctx)
}

// ListAdCandidates mocks base method.
func (m *MockAdRepository) ListAdCandidates(ctx context.Context, spendDate time.Time) ([]*models.AdCandidate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAdCandidates", ctx, spendDate)
	ret0, _ := ret[0].([]*models.AdCandidate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAdCandidates indicates an expected call of ListAdCandidates.
func (mr *MockAdRepositoryMockRecorder) ListAdCandidates(ctx, spendDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAdCandidates", reflect.TypeOf((*MockAdRepository)(nil).ListAdCandidates), ctx, spendDate)
}

// ListByAdCampaignID mocks base method.
func (m *MockAdRepository) ListByAdCampaignID(ctx context.Context, campaignID int) ([]*models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAdCampaignID", ctx, campaignID)
	ret0, _ := ret[0].([]*models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAdCampaignID indicates an expected call of ListByAdCampaignID.
func (mr *MockAdRepositoryMockRecorder) ListByAdCampaignID(ctx, campaignID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAdCampaignID", reflect.TypeOf((*MockAdRepository)(nil).ListByAdCampaignID), ctx, campaignID)
}

// ListByStatus mocks base method.
func (m *MockAdRepository) ListByStatus(ctx context.Context, status models.AdStatus) ([]*models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStatus", ctx, status)
	ret0, _ := ret[0].([]*models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByStatus indicates an expected call of ListByStatus.
func (mr *MockAdRepositoryMockRecorder) ListByStatus(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStatus", reflect.TypeOf((*MockAdRepository)(nil).ListByStatus), ctx, status)
}

// ListByAdGroupID mocks base method.
func (m *MockAdRepository) ListByAdGroupID(ctx context.Context, adGroupID int) ([]*models.Ad, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAdGroupID", ctx, adGroupID)
	ret0, _ := ret[0].([]*models.Ad)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAdGroupID indicates an expected call of ListByAdGroupID.
func (mr *MockAdRepositoryMockRecorder) ListByAdGroupID(ctx, adGroupID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAdGroupID", reflect.TypeOf((*MockAdRepository)(nil).ListByAdGroupID), ctx, adGroupID)
}

// ReserveImpression mocks base method.
func (m *MockAdRepository) ReserveImpression(ctx context.Context, reservation models.ImpressionReservation) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReserveImpression", ctx, reservation)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReserveImpression indicates an expected call of ReserveImpression.
func (mr *MockAdRepositoryMockRecorder) ReserveImpression(ctx, reservation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReserveImpression", reflect.TypeOf((*MockAdRepository)(nil).ReserveImpression), ctx, reservation)
}

// Update mocks base method.
func (m *MockAdRepository) Update(ctx context.Context, ad *models.Ad) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, ad)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAdRepositoryMockRecorder) Update(ctx, ad any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAdRepository)(nil).Update), ctx, ad)
}

// UpdateStatusByCampaignID mocks base method.
func (m *MockAdRepository) UpdateStatusByCampaignID(ctx context.Context, campaignID int, status models.AdStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatusByCampaignID", ctx, campaignID, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatusByCampaignID indicates an expected call of UpdateStatusByCampaignID.
func (mr *MockAdRepositoryMockRecorder) UpdateStatusByCampaignID(ctx, campaignID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatusByCampaignID", reflect.TypeOf((*MockAdRepository)(nil).UpdateStatusByCampaignID), ctx, campaignID, status)
}

// UpdateImage mocks base method.
func (m *MockAdRepository) UpdateImage(ctx context.Context, adID int, imageKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateImage", ctx, adID, imageKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateImage indicates an expected call of UpdateImage.
func (mr *MockAdRepositoryMockRecorder) UpdateImage(ctx, adID, imageKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateImage", reflect.TypeOf((*MockAdRepository)(nil).UpdateImage), ctx, adID, imageKey)
}

// MockFeedLinkRepository is a mock of FeedLinkRepository interface.
type MockFeedLinkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockFeedLinkRepositoryMockRecorder
	isgomock struct{}
}

// MockFeedLinkRepositoryMockRecorder is the mock recorder for MockFeedLinkRepository.
type MockFeedLinkRepositoryMockRecorder struct {
	mock *MockFeedLinkRepository
}

// NewMockFeedLinkRepository creates a new mock instance.
func NewMockFeedLinkRepository(ctrl *gomock.Controller) *MockFeedLinkRepository {
	mock := &MockFeedLinkRepository{ctrl: ctrl}
	mock.recorder = &MockFeedLinkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFeedLinkRepository) EXPECT() *MockFeedLinkRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockFeedLinkRepository) Create(ctx context.Context, advertiserID int, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, advertiserID, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockFeedLinkRepositoryMockRecorder) Create(ctx, advertiserID, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockFeedLinkRepository)(nil).Create), ctx, advertiserID, token)
}

// GetCampaignIDByToken mocks base method.
func (m *MockFeedLinkRepository) GetCampaignIDByToken(ctx context.Context, token string) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCampaignIDByToken", ctx, token)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCampaignIDByToken indicates an expected call of GetCampaignIDByToken.
func (mr *MockFeedLinkRepositoryMockRecorder) GetCampaignIDByToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCampaignIDByToken", reflect.TypeOf((*MockFeedLinkRepository)(nil).GetCampaignIDByToken), ctx, token)
}

// MockAvatarStorage is a mock of AvatarStorage interface.
type MockAvatarStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarStorageMockRecorder
	isgomock struct{}
}

// MockAvatarStorageMockRecorder is the mock recorder for MockAvatarStorage.
type MockAvatarStorageMockRecorder struct {
	mock *MockAvatarStorage
}

// NewMockAvatarStorage creates a new mock instance.
func NewMockAvatarStorage(ctrl *gomock.Controller) *MockAvatarStorage {
	mock := &MockAvatarStorage{ctrl: ctrl}
	mock.recorder = &MockAvatarStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarStorage) EXPECT() *MockAvatarStorageMockRecorder {
	return m.recorder
}

// DeleteAvatar mocks base method.
func (m *MockAvatarStorage) DeleteAvatar(ctx context.Context, advertiserID int, avatarKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAvatar", ctx, advertiserID, avatarKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAvatar indicates an expected call of DeleteAvatar.
func (mr *MockAvatarStorageMockRecorder) DeleteAvatar(ctx, advertiserID, avatarKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAvatar", reflect.TypeOf((*MockAvatarStorage)(nil).DeleteAvatar), ctx, advertiserID, avatarKey)
}

// GetAvatarURL mocks base method.
func (m *MockAvatarStorage) GetAvatarURL(avatarKey string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvatarURL", avatarKey)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAvatarURL indicates an expected call of GetAvatarURL.
func (mr *MockAvatarStorageMockRecorder) GetAvatarURL(avatarKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvatarURL", reflect.TypeOf((*MockAvatarStorage)(nil).GetAvatarURL), avatarKey)
}

// UploadAvatar mocks base method.
func (m *MockAvatarStorage) UploadAvatar(ctx context.Context, advertiserID int, data []byte, ext, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", ctx, advertiserID, data, ext, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockAvatarStorageMockRecorder) UploadAvatar(ctx, advertiserID, data, ext, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockAvatarStorage)(nil).UploadAvatar), ctx, advertiserID, data, ext, contentType)
}

// MockAppealStorage is a mock of AppealStorage interface.
type MockAppealStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAppealStorageMockRecorder
	isgomock struct{}
}

// MockAppealStorageMockRecorder is the mock recorder for MockAppealStorage.
type MockAppealStorageMockRecorder struct {
	mock *MockAppealStorage
}

// NewMockAppealStorage creates a new mock instance.
func NewMockAppealStorage(ctrl *gomock.Controller) *MockAppealStorage {
	mock := &MockAppealStorage{ctrl: ctrl}
	mock.recorder = &MockAppealStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppealStorage) EXPECT() *MockAppealStorageMockRecorder {
	return m.recorder
}

// DeleteAppealImage mocks base method.
func (m *MockAppealStorage) DeleteAppealImage(ctx context.Context, appealID int, imageKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAppealImage", ctx, appealID, imageKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAppealImage indicates an expected call of DeleteAppealImage.
func (mr *MockAppealStorageMockRecorder) DeleteAppealImage(ctx, appealID, imageKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAppealImage", reflect.TypeOf((*MockAppealStorage)(nil).DeleteAppealImage), ctx, appealID, imageKey)
}

// GetAppealImageURL mocks base method.
func (m *MockAppealStorage) GetAppealImageURL(imageKey string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAppealImageURL", imageKey)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAppealImageURL indicates an expected call of GetAppealImageURL.
func (mr *MockAppealStorageMockRecorder) GetAppealImageURL(imageKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAppealImageURL", reflect.TypeOf((*MockAppealStorage)(nil).GetAppealImageURL), imageKey)
}

// UploadAppealImage mocks base method.
func (m *MockAppealStorage) UploadAppealImage(ctx context.Context, appealID int, data []byte, ext, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAppealImage", ctx, appealID, data, ext, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAppealImage indicates an expected call of UploadAppealImage.
func (mr *MockAppealStorageMockRecorder) UploadAppealImage(ctx, appealID, data, ext, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAppealImage", reflect.TypeOf((*MockAppealStorage)(nil).UploadAppealImage), ctx, appealID, data, ext, contentType)
}

// MockAdStorage is a mock of AdStorage interface.
type MockAdStorage struct {
	ctrl     *gomock.Controller
	recorder *MockAdStorageMockRecorder
	isgomock struct{}
}

// MockAdStorageMockRecorder is the mock recorder for MockAdStorage.
type MockAdStorageMockRecorder struct {
	mock *MockAdStorage
}

// NewMockAdStorage creates a new mock instance.
func NewMockAdStorage(ctrl *gomock.Controller) *MockAdStorage {
	mock := &MockAdStorage{ctrl: ctrl}
	mock.recorder = &MockAdStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdStorage) EXPECT() *MockAdStorageMockRecorder {
	return m.recorder
}

// DeleteAdImage mocks base method.
func (m *MockAdStorage) DeleteAdImage(ctx context.Context, imageKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAdImage", ctx, imageKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAdImage indicates an expected call of DeleteAdImage.
func (mr *MockAdStorageMockRecorder) DeleteAdImage(ctx, imageKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAdImage", reflect.TypeOf((*MockAdStorage)(nil).DeleteAdImage), ctx, imageKey)
}

// GetAdImageURL mocks base method.
func (m *MockAdStorage) GetAdImageURL(imagKey string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdImageURL", imagKey)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAdImageURL indicates an expected call of GetAdImageURL.
func (mr *MockAdStorageMockRecorder) GetAdImageURL(imagKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdImageURL", reflect.TypeOf((*MockAdStorage)(nil).GetAdImageURL), imagKey)
}

// UploadAdImage mocks base method.
func (m *MockAdStorage) UploadAdImage(ctx context.Context, data []byte, ext, contentType string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAdImage", ctx, data, ext, contentType)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAdImage indicates an expected call of UploadAdImage.
func (mr *MockAdStorageMockRecorder) UploadAdImage(ctx, data, ext, contentType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAdImage", reflect.TypeOf((*MockAdStorage)(nil).UploadAdImage), ctx, data, ext, contentType)
}

// MockAdActionRepository is a mock of AdActionRepository interface.
type MockAdActionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAdActionRepositoryMockRecorder
	isgomock struct{}
}

// MockAdActionRepositoryMockRecorder is the mock recorder for MockAdActionRepository.
type MockAdActionRepositoryMockRecorder struct {
	mock *MockAdActionRepository
}

// NewMockAdActionRepository creates a new mock instance.
func NewMockAdActionRepository(ctrl *gomock.Controller) *MockAdActionRepository {
	mock := &MockAdActionRepository{ctrl: ctrl}
	mock.recorder = &MockAdActionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdActionRepository) EXPECT() *MockAdActionRepositoryMockRecorder {
	return m.recorder
}

// MockTopicRepository is a mock of TopicRepository interface.
type MockTopicRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTopicRepositoryMockRecorder
	isgomock struct{}
}

// MockTopicRepositoryMockRecorder is the mock recorder for MockTopicRepository.
type MockTopicRepositoryMockRecorder struct {
	mock *MockTopicRepository
}

// NewMockTopicRepository creates a new mock instance.
func NewMockTopicRepository(ctrl *gomock.Controller) *MockTopicRepository {
	mock := &MockTopicRepository{ctrl: ctrl}
	mock.recorder = &MockTopicRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTopicRepository) EXPECT() *MockTopicRepositoryMockRecorder {
	return m.recorder
}

// MockRegionRepository is a mock of RegionRepository interface.
type MockRegionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRegionRepositoryMockRecorder
	isgomock struct{}
}

// MockRegionRepositoryMockRecorder is the mock recorder for MockRegionRepository.
type MockRegionRepositoryMockRecorder struct {
	mock *MockRegionRepository
}

// NewMockRegionRepository creates a new mock instance.
func NewMockRegionRepository(ctrl *gomock.Controller) *MockRegionRepository {
	mock := &MockRegionRepository{ctrl: ctrl}
	mock.recorder = &MockRegionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegionRepository) EXPECT() *MockRegionRepositoryMockRecorder {
	return m.recorder
}

// MockAppealRepository is a mock of AppealRepository interface.
type MockAppealRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAppealRepositoryMockRecorder
	isgomock struct{}
}

// MockAppealRepositoryMockRecorder is the mock recorder for MockAppealRepository.
type MockAppealRepositoryMockRecorder struct {
	mock *MockAppealRepository
}

// NewMockAppealRepository creates a new mock instance.
func NewMockAppealRepository(ctrl *gomock.Controller) *MockAppealRepository {
	mock := &MockAppealRepository{ctrl: ctrl}
	mock.recorder = &MockAppealRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppealRepository) EXPECT() *MockAppealRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAppealRepository) Create(ctx context.Context, appeal *models.Appeal) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, appeal)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAppealRepositoryMockRecorder) Create(ctx, appeal any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAppealRepository)(nil).Create), ctx, appeal)
}

// GetByID mocks base method.
func (m *MockAppealRepository) GetByID(ctx context.Context, appealID int) (*models.Appeal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, appealID)
	ret0, _ := ret[0].(*models.Appeal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAppealRepositoryMockRecorder) GetByID(ctx, appealID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAppealRepository)(nil).GetByID), ctx, appealID)
}

// ListByAdvertiserID mocks base method.
func (m *MockAppealRepository) ListByAdvertiserID(ctx context.Context, advertiserID int) ([]*models.Appeal, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAdvertiserID", ctx, advertiserID)
	ret0, _ := ret[0].([]*models.Appeal)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByAdvertiserID indicates an expected call of ListByAdvertiserID.
func (mr *MockAppealRepositoryMockRecorder) ListByAdvertiserID(ctx, advertiserID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAdvertiserID", reflect.TypeOf((*MockAppealRepository)(nil).ListByAdvertiserID), ctx, advertiserID)
}

// UpdateImage mocks base method.
func (m *MockAppealRepository) UpdateImage(ctx context.Context, appealID int, imageKey string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateImage", ctx, appealID, imageKey)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateImage indicates an expected call of UpdateImage.
func (mr *MockAppealRepositoryMockRecorder) UpdateImage(ctx, appealID, imageKey any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateImage", reflect.TypeOf((*MockAppealRepository)(nil).UpdateImage), ctx, appealID, imageKey)
}
