// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson1ff0c272DecodeEshkereInternalHandlerV1Dto(in *jlexer.Lexer, out *UpdateAdCampaignRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				*out.Name = string(in.String())
			}
		case "daily_budget":
			if in.IsNull() {
				in.Skip()
				out.DailyBudget = nil
			} else {
				if out.DailyBudget == nil {
					out.DailyBudget = new(int64)
				}
				*out.DailyBudget = int64(in.Int64())
			}
		case "cpm_price":
			if in.IsNull() {
				in.Skip()
				out.CPMPrice = nil
			} else {
				if out.CPMPrice == nil {
					out.CPMPrice = new(int64)
				}
				*out.CPMPrice = int64(in.Int64())
			}
		case "main_action":
			if in.IsNull() {
				in.Skip()
				out.MainAction = nil
			} else {
				if out.MainAction == nil {
					out.MainAction = new(string)
				}
				*out.MainAction = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1ff0c272EncodeEshkereInternalHandlerV1Dto(out *jwriter.Writer, in UpdateAdCampaignRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		if in.Name == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Name))
		}
	}
	{
		const prefix string = ",\"daily_budget\":"
		out.RawString(prefix)
		if in.DailyBudget == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.DailyBudget))
		}
	}
	{
		const prefix string = ",\"cpm_price\":"
		out.RawString(prefix)
		if in.CPMPrice == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.CPMPrice))
		}
	}
	{
		const prefix string = ",\"main_action\":"
		out.RawString(prefix)
		if in.MainAction == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.MainAction))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateAdCampaignRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1ff0c272EncodeEshkereInternalHandlerV1Dto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateAdCampaignRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1ff0c272EncodeEshkereInternalHandlerV1Dto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateAdCampaignRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1ff0c272DecodeEshkereInternalHandlerV1Dto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateAdCampaignRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1ff0c272DecodeEshkereInternalHandlerV1Dto(l, v)
}
func easyjson1ff0c272DecodeEshkereInternalHandlerV1Dto1(in *jlexer.Lexer, out *ListAdCampaignsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "advertiser_id":
			out.AdvertiserID = int(in.Int())
		case "campaigns":
			if in.IsNull() {
				in.Skip()
				out.Campaigns = nil
			} else {
				in.Delim('[')
				if out.Campaigns == nil {
					if !in.IsDelim(']') {
						out.Campaigns = make([]*AdCampaignResponse, 0, 8)
					} else {
						out.Campaigns = []*AdCampaignResponse{}
					}
				} else {
					out.Campaigns = (out.Campaigns)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *AdCampaignResponse
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(AdCampaignResponse)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.Campaigns = append(out.Campaigns, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1ff0c272EncodeEshkereInternalHandlerV1Dto1(out *jwriter.Writer, in ListAdCampaignsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"advertiser_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.AdvertiserID))
	}
	{
		const prefix string = ",\"campaigns\":"
		out.RawString(prefix)
		if in.Campaigns == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Campaigns {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListAdCampaignsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1ff0c272EncodeEshkereInternalHandlerV1Dto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListAdCampaignsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1ff0c272EncodeEshkereInternalHandlerV1Dto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListAdCampaignsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1ff0c272DecodeEshkereInternalHandlerV1Dto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListAdCampaignsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1ff0c272DecodeEshkereInternalHandlerV1Dto1(l, v)
}
func easyjson1ff0c272DecodeEshkereInternalHandlerV1Dto2(in *jlexer.Lexer, out *CreateAdCampaignResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1ff0c272EncodeEshkereInternalHandlerV1Dto2(out *jwriter.Writer, in CreateAdCampaignResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateAdCampaignResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1ff0c272EncodeEshkereInternalHandlerV1Dto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateAdCampaignResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1ff0c272EncodeEshkereInternalHandlerV1Dto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateAdCampaignResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1ff0c272DecodeEshkereInternalHandlerV1Dto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateAdCampaignResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1ff0c272DecodeEshkereInternalHandlerV1Dto2(l, v)
}
func easyjson1ff0c272DecodeEshkereInternalHandlerV1Dto3(in *jlexer.Lexer, out *CreateAdCampaignRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "daily_budget":
			out.DailyBudget = int64(in.Int64())
		case "cpm_price":
			out.CPMPrice = int64(in.Int64())
		case "main_action":
			out.MainAction = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1ff0c272EncodeEshkereInternalHandlerV1Dto3(out *jwriter.Writer, in CreateAdCampaignRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"daily_budget\":"
		out.RawString(prefix)
		out.Int64(int64(in.DailyBudget))
	}
	{
		const prefix string = ",\"cpm_price\":"
		out.RawString(prefix)
		out.Int64(int64(in.CPMPrice))
	}
	{
		const prefix string = ",\"main_action\":"
		out.RawString(prefix)
		out.String(string(in.MainAction))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateAdCampaignRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1ff0c272EncodeEshkereInternalHandlerV1Dto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateAdCampaignRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1ff0c272EncodeEshkereInternalHandlerV1Dto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateAdCampaignRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1ff0c272DecodeEshkereInternalHandlerV1Dto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateAdCampaignRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1ff0c272DecodeEshkereInternalHandlerV1Dto3(l, v)
}
func easyjson1ff0c272DecodeEshkereInternalHandlerV1Dto4(in *jlexer.Lexer, out *AdCampaignResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "status":
			out.Status = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "daily_budget":
			out.DailyBudget = int64(in.Int64())
		case "cpm_price":
			out.CPMPrice = int64(in.Int64())
		case "main_action":
			out.MainAction = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson1ff0c272EncodeEshkereInternalHandlerV1Dto4(out *jwriter.Writer, in AdCampaignResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"daily_budget\":"
		out.RawString(prefix)
		out.Int64(int64(in.DailyBudget))
	}
	{
		const prefix string = ",\"cpm_price\":"
		out.RawString(prefix)
		out.Int64(int64(in.CPMPrice))
	}
	{
		const prefix string = ",\"main_action\":"
		out.RawString(prefix)
		out.String(string(in.MainAction))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdCampaignResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson1ff0c272EncodeEshkereInternalHandlerV1Dto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdCampaignResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson1ff0c272EncodeEshkereInternalHandlerV1Dto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdCampaignResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson1ff0c272DecodeEshkereInternalHandlerV1Dto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdCampaignResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson1ff0c272DecodeEshkereInternalHandlerV1Dto4(l, v)
}
