// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto(in *jlexer.Lexer, out *UpdateAdRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ID":
			out.ID = int(in.Int())
		case "title":
			if in.IsNull() {
				in.Skip()
				out.Title = nil
			} else {
				if out.Title == nil {
					out.Title = new(string)
				}
				*out.Title = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
				out.Status = nil
			} else {
				if out.Status == nil {
					out.Status = new(string)
				}
				*out.Status = string(in.String())
			}
		case "short_desc":
			if in.IsNull() {
				in.Skip()
				out.ShortDesc = nil
			} else {
				if out.ShortDesc == nil {
					out.ShortDesc = new(string)
				}
				*out.ShortDesc = string(in.String())
			}
		case "target_url":
			if in.IsNull() {
				in.Skip()
				out.TargetURL = nil
			} else {
				if out.TargetURL == nil {
					out.TargetURL = new(string)
				}
				*out.TargetURL = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto(out *jwriter.Writer, in UpdateAdRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ID\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		if in.Title == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Title))
		}
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		if in.Status == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Status))
		}
	}
	{
		const prefix string = ",\"short_desc\":"
		out.RawString(prefix)
		if in.ShortDesc == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.ShortDesc))
		}
	}
	{
		const prefix string = ",\"target_url\":"
		out.RawString(prefix)
		if in.TargetURL == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.TargetURL))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateAdRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateAdRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateAdRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateAdRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto(l, v)
}
func easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto1(in *jlexer.Lexer, out *ListAdsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "group_id":
			out.GroupID = int(in.Int())
		case "ads":
			if in.IsNull() {
				in.Skip()
				out.Ads = nil
			} else {
				in.Delim('[')
				if out.Ads == nil {
					if !in.IsDelim(']') {
						out.Ads = make([]*AdResponse, 0, 8)
					} else {
						out.Ads = []*AdResponse{}
					}
				} else {
					out.Ads = (out.Ads)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *AdResponse
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(AdResponse)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.Ads = append(out.Ads, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto1(out *jwriter.Writer, in ListAdsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"group_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.GroupID))
	}
	{
		const prefix string = ",\"ads\":"
		out.RawString(prefix)
		if in.Ads == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Ads {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListAdsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListAdsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListAdsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListAdsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto1(l, v)
}
func easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto2(in *jlexer.Lexer, out *CreateAdResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto2(out *jwriter.Writer, in CreateAdResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateAdResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateAdResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateAdResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateAdResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto2(l, v)
}
func easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto3(in *jlexer.Lexer, out *CreateAdRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "title":
			out.Title = string(in.String())
		case "short_desc":
			out.ShortDesc = string(in.String())
		case "target_url":
			out.TargetURL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto3(out *jwriter.Writer, in CreateAdRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix[1:])
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"short_desc\":"
		out.RawString(prefix)
		out.String(string(in.ShortDesc))
	}
	{
		const prefix string = ",\"target_url\":"
		out.RawString(prefix)
		out.String(string(in.TargetURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateAdRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateAdRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateAdRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateAdRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto3(l, v)
}
func easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto4(in *jlexer.Lexer, out *AdResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "status":
			out.Status = string(in.String())
		case "title":
			out.Title = string(in.String())
		case "short_desc":
			out.ShortDesc = string(in.String())
		case "image_url":
			out.ImageURL = string(in.String())
		case "target_url":
			out.TargetURL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto4(out *jwriter.Writer, in AdResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"short_desc\":"
		out.RawString(prefix)
		out.String(string(in.ShortDesc))
	}
	{
		const prefix string = ",\"image_url\":"
		out.RawString(prefix)
		out.String(string(in.ImageURL))
	}
	{
		const prefix string = ",\"target_url\":"
		out.RawString(prefix)
		out.String(string(in.TargetURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto4(l, v)
}
func easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto5(in *jlexer.Lexer, out *AdRequestResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "request_id":
			out.RequestID = string(in.String())
		case "ad":
			if in.IsNull() {
				in.Skip()
				out.Ad = nil
			} else {
				if out.Ad == nil {
					out.Ad = new(AdResponse)
				}
				(*out.Ad).UnmarshalEasyJSON(in)
			}
		case "click_url":
			out.ClickURL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto5(out *jwriter.Writer, in AdRequestResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"request_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.RequestID))
	}
	{
		const prefix string = ",\"ad\":"
		out.RawString(prefix)
		if in.Ad == nil {
			out.RawString("null")
		} else {
			(*in.Ad).MarshalEasyJSON(out)
		}
	}
	{
		const prefix string = ",\"click_url\":"
		out.RawString(prefix)
		out.String(string(in.ClickURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdRequestResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdRequestResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdRequestResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdRequestResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto5(l, v)
}
func easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto6(in *jlexer.Lexer, out *AdRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "embed_token":
			out.EmbedToken = string(in.String())
		case "visitor_id":
			out.VisitorID = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto6(out *jwriter.Writer, in AdRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"embed_token\":"
		out.RawString(prefix[1:])
		out.String(string(in.EmbedToken))
	}
	{
		const prefix string = ",\"visitor_id\":"
		out.RawString(prefix)
		out.String(string(in.VisitorID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson63cbde9bEncodeEshkereInternalHandlerV1Dto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson63cbde9bDecodeEshkereInternalHandlerV1Dto6(l, v)
}
