// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson92a79907DecodeEshkereInternalHandlerV1Dto(in *jlexer.Lexer, out *UpdateAdGroupRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "topic_id":
			if in.IsNull() {
				in.Skip()
				out.TopicID = nil
			} else {
				if out.TopicID == nil {
					out.TopicID = new(int)
				}
				*out.TopicID = int(in.Int())
			}
		case "region_id":
			if in.IsNull() {
				in.Skip()
				out.RegionID = nil
			} else {
				if out.RegionID == nil {
					out.RegionID = new(int)
				}
				*out.RegionID = int(in.Int())
			}
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				*out.Name = string(in.String())
			}
		case "age_from":
			if in.IsNull() {
				in.Skip()
				out.AgeFrom = nil
			} else {
				if out.AgeFrom == nil {
					out.AgeFrom = new(int)
				}
				*out.AgeFrom = int(in.Int())
			}
		case "age_to":
			if in.IsNull() {
				in.Skip()
				out.AgeTo = nil
			} else {
				if out.AgeTo == nil {
					out.AgeTo = new(int)
				}
				*out.AgeTo = int(in.Int())
			}
		case "gender":
			if in.IsNull() {
				in.Skip()
				out.Gender = nil
			} else {
				if out.Gender == nil {
					out.Gender = new(string)
				}
				*out.Gender = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson92a79907EncodeEshkereInternalHandlerV1Dto(out *jwriter.Writer, in UpdateAdGroupRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"topic_id\":"
		out.RawString(prefix[1:])
		if in.TopicID == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.TopicID))
		}
	}
	{
		const prefix string = ",\"region_id\":"
		out.RawString(prefix)
		if in.RegionID == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.RegionID))
		}
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		if in.Name == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Name))
		}
	}
	{
		const prefix string = ",\"age_from\":"
		out.RawString(prefix)
		if in.AgeFrom == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.AgeFrom))
		}
	}
	{
		const prefix string = ",\"age_to\":"
		out.RawString(prefix)
		if in.AgeTo == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.AgeTo))
		}
	}
	{
		const prefix string = ",\"gender\":"
		out.RawString(prefix)
		if in.Gender == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Gender))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateAdGroupRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson92a79907EncodeEshkereInternalHandlerV1Dto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateAdGroupRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson92a79907EncodeEshkereInternalHandlerV1Dto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateAdGroupRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson92a79907DecodeEshkereInternalHandlerV1Dto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateAdGroupRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson92a79907DecodeEshkereInternalHandlerV1Dto(l, v)
}
func easyjson92a79907DecodeEshkereInternalHandlerV1Dto1(in *jlexer.Lexer, out *ListAdGroupsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "ad_campaign_id":
			out.AdCampaignID = int(in.Int())
		case "groups":
			if in.IsNull() {
				in.Skip()
				out.Groups = nil
			} else {
				in.Delim('[')
				if out.Groups == nil {
					if !in.IsDelim(']') {
						out.Groups = make([]*AdGroupResponse, 0, 8)
					} else {
						out.Groups = []*AdGroupResponse{}
					}
				} else {
					out.Groups = (out.Groups)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *AdGroupResponse
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(AdGroupResponse)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.Groups = append(out.Groups, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson92a79907EncodeEshkereInternalHandlerV1Dto1(out *jwriter.Writer, in ListAdGroupsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"ad_campaign_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.AdCampaignID))
	}
	{
		const prefix string = ",\"groups\":"
		out.RawString(prefix)
		if in.Groups == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Groups {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListAdGroupsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson92a79907EncodeEshkereInternalHandlerV1Dto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListAdGroupsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson92a79907EncodeEshkereInternalHandlerV1Dto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListAdGroupsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson92a79907DecodeEshkereInternalHandlerV1Dto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListAdGroupsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson92a79907DecodeEshkereInternalHandlerV1Dto1(l, v)
}
func easyjson92a79907DecodeEshkereInternalHandlerV1Dto2(in *jlexer.Lexer, out *CreateAdGroupResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson92a79907EncodeEshkereInternalHandlerV1Dto2(out *jwriter.Writer, in CreateAdGroupResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateAdGroupResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson92a79907EncodeEshkereInternalHandlerV1Dto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateAdGroupResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson92a79907EncodeEshkereInternalHandlerV1Dto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateAdGroupResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson92a79907DecodeEshkereInternalHandlerV1Dto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateAdGroupResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson92a79907DecodeEshkereInternalHandlerV1Dto2(l, v)
}
func easyjson92a79907DecodeEshkereInternalHandlerV1Dto3(in *jlexer.Lexer, out *CreateAdGroupRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "topic_id":
			out.TopicID = int(in.Int())
		case "region_id":
			out.RegionID = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "age_from":
			out.AgeFrom = int(in.Int())
		case "age_to":
			out.AgeTo = int(in.Int())
		case "gender":
			out.Gender = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson92a79907EncodeEshkereInternalHandlerV1Dto3(out *jwriter.Writer, in CreateAdGroupRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"topic_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.TopicID))
	}
	{
		const prefix string = ",\"region_id\":"
		out.RawString(prefix)
		out.Int(int(in.RegionID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"age_from\":"
		out.RawString(prefix)
		out.Int(int(in.AgeFrom))
	}
	{
		const prefix string = ",\"age_to\":"
		out.RawString(prefix)
		out.Int(int(in.AgeTo))
	}
	{
		const prefix string = ",\"gender\":"
		out.RawString(prefix)
		out.String(string(in.Gender))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateAdGroupRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson92a79907EncodeEshkereInternalHandlerV1Dto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateAdGroupRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson92a79907EncodeEshkereInternalHandlerV1Dto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateAdGroupRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson92a79907DecodeEshkereInternalHandlerV1Dto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateAdGroupRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson92a79907DecodeEshkereInternalHandlerV1Dto3(l, v)
}
func easyjson92a79907DecodeEshkereInternalHandlerV1Dto4(in *jlexer.Lexer, out *AdGroupResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "topic_id":
			out.TopicID = int(in.Int())
		case "region_id":
			out.RegionID = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "age_from":
			out.AgeFrom = int(in.Int())
		case "age_to":
			out.AgeTo = int(in.Int())
		case "gender":
			out.Gender = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson92a79907EncodeEshkereInternalHandlerV1Dto4(out *jwriter.Writer, in AdGroupResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"topic_id\":"
		out.RawString(prefix)
		out.Int(int(in.TopicID))
	}
	{
		const prefix string = ",\"region_id\":"
		out.RawString(prefix)
		out.Int(int(in.RegionID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"age_from\":"
		out.RawString(prefix)
		out.Int(int(in.AgeFrom))
	}
	{
		const prefix string = ",\"age_to\":"
		out.RawString(prefix)
		out.Int(int(in.AgeTo))
	}
	{
		const prefix string = ",\"gender\":"
		out.RawString(prefix)
		out.String(string(in.Gender))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdGroupResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson92a79907EncodeEshkereInternalHandlerV1Dto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdGroupResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson92a79907EncodeEshkereInternalHandlerV1Dto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdGroupResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson92a79907DecodeEshkereInternalHandlerV1Dto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdGroupResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson92a79907DecodeEshkereInternalHandlerV1Dto4(l, v)
}
