// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto(in *jlexer.Lexer, out *VKIDLoginRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "access_token":
			out.AccessToken = string(in.String())
		case "user_id":
			out.UserID = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto(out *jwriter.Writer, in VKIDLoginRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"access_token\":"
		out.RawString(prefix[1:])
		out.String(string(in.AccessToken))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.Int64(int64(in.UserID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v VKIDLoginRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v VKIDLoginRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *VKIDLoginRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *VKIDLoginRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto(l, v)
}
func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto1(in *jlexer.Lexer, out *UpdateAdvertiserProfileRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				*out.Name = string(in.String())
			}
		case "surname":
			if in.IsNull() {
				in.Skip()
				out.Surname = nil
			} else {
				if out.Surname == nil {
					out.Surname = new(string)
				}
				*out.Surname = string(in.String())
			}
		case "email":
			if in.IsNull() {
				in.Skip()
				out.Email = nil
			} else {
				if out.Email == nil {
					out.Email = new(string)
				}
				*out.Email = string(in.String())
			}
		case "phone":
			if in.IsNull() {
				in.Skip()
				out.Phone = nil
			} else {
				if out.Phone == nil {
					out.Phone = new(string)
				}
				*out.Phone = string(in.String())
			}
		case "company":
			if in.IsNull() {
				in.Skip()
				out.Company = nil
			} else {
				if out.Company == nil {
					out.Company = new(string)
				}
				*out.Company = string(in.String())
			}
		case "city":
			if in.IsNull() {
				in.Skip()
				out.City = nil
			} else {
				if out.City == nil {
					out.City = new(string)
				}
				*out.City = string(in.String())
			}
		case "tariff":
			if in.IsNull() {
				in.Skip()
				out.Tariff = nil
			} else {
				if out.Tariff == nil {
					out.Tariff = new(string)
				}
				*out.Tariff = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto1(out *jwriter.Writer, in UpdateAdvertiserProfileRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		if in.Name == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Name))
		}
	}
	{
		const prefix string = ",\"surname\":"
		out.RawString(prefix)
		if in.Surname == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Surname))
		}
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		if in.Email == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Email))
		}
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		if in.Phone == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Phone))
		}
	}
	{
		const prefix string = ",\"company\":"
		out.RawString(prefix)
		if in.Company == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Company))
		}
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		if in.City == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.City))
		}
	}
	{
		const prefix string = ",\"tariff\":"
		out.RawString(prefix)
		if in.Tariff == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Tariff))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdateAdvertiserProfileRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdateAdvertiserProfileRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdateAdvertiserProfileRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdateAdvertiserProfileRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto1(l, v)
}
func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto2(in *jlexer.Lexer, out *TopUpBalanceRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount":
			out.Amount = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto2(out *jwriter.Writer, in TopUpBalanceRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Amount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v TopUpBalanceRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TopUpBalanceRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TopUpBalanceRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TopUpBalanceRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto2(l, v)
}
func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto3(in *jlexer.Lexer, out *RegisterResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "email":
			out.Email = string(in.String())
		case "phone":
			out.Phone = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto3(out *jwriter.Writer, in RegisterResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RegisterResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RegisterResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RegisterResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RegisterResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto3(l, v)
}
func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto4(in *jlexer.Lexer, out *RegisterRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			out.Name = string(in.String())
		case "email":
			out.Email = string(in.String())
		case "phone":
			out.Phone = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto4(out *jwriter.Writer, in RegisterRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v RegisterRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v RegisterRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *RegisterRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *RegisterRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto4(l, v)
}
func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto5(in *jlexer.Lexer, out *NotificationSettingsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email_enabled":
			out.EmailEnabled = bool(in.Bool())
		case "warning_threshold":
			out.WarningThreshold = int64(in.Int64())
		case "critical_threshold":
			out.CriticalThreshold = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto5(out *jwriter.Writer, in NotificationSettingsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email_enabled\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.EmailEnabled))
	}
	{
		const prefix string = ",\"warning_threshold\":"
		out.RawString(prefix)
		out.Int64(int64(in.WarningThreshold))
	}
	{
		const prefix string = ",\"critical_threshold\":"
		out.RawString(prefix)
		out.Int64(int64(in.CriticalThreshold))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NotificationSettingsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NotificationSettingsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NotificationSettingsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NotificationSettingsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto5(l, v)
}
func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto6(in *jlexer.Lexer, out *NotificationSettingsRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "email_enabled":
			out.EmailEnabled = bool(in.Bool())
		case "warning_threshold":
			out.WarningThreshold = int64(in.Int64())
		case "critical_threshold":
			out.CriticalThreshold = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto6(out *jwriter.Writer, in NotificationSettingsRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"email_enabled\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.EmailEnabled))
	}
	{
		const prefix string = ",\"warning_threshold\":"
		out.RawString(prefix)
		out.Int64(int64(in.WarningThreshold))
	}
	{
		const prefix string = ",\"critical_threshold\":"
		out.RawString(prefix)
		out.Int64(int64(in.CriticalThreshold))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v NotificationSettingsRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v NotificationSettingsRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *NotificationSettingsRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *NotificationSettingsRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto6(l, v)
}
func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto7(in *jlexer.Lexer, out *LoginResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "email":
			out.Email = string(in.String())
		case "phone":
			out.Phone = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto7(out *jwriter.Writer, in LoginResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LoginResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LoginResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LoginResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LoginResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto7(l, v)
}
func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto8(in *jlexer.Lexer, out *LoginRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "identifier":
			out.Identifier = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto8(out *jwriter.Writer, in LoginRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"identifier\":"
		out.RawString(prefix[1:])
		out.String(string(in.Identifier))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v LoginRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v LoginRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *LoginRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *LoginRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto8(l, v)
}
func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto9(in *jlexer.Lexer, out *DeliveryAlertResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "level":
			out.Level = string(in.String())
		case "title":
			out.Title = string(in.String())
		case "message":
			out.Message = string(in.String())
		case "active_campaigns":
			out.ActiveCampaigns = int(in.Int())
		case "affected_campaigns":
			out.AffectedCampaigns = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto9(out *jwriter.Writer, in DeliveryAlertResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"level\":"
		out.RawString(prefix[1:])
		out.String(string(in.Level))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"message\":"
		out.RawString(prefix)
		out.String(string(in.Message))
	}
	{
		const prefix string = ",\"active_campaigns\":"
		out.RawString(prefix)
		out.Int(int(in.ActiveCampaigns))
	}
	{
		const prefix string = ",\"affected_campaigns\":"
		out.RawString(prefix)
		out.Int(int(in.AffectedCampaigns))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v DeliveryAlertResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v DeliveryAlertResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *DeliveryAlertResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *DeliveryAlertResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto9(l, v)
}
func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto10(in *jlexer.Lexer, out *CreatePaymentResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "payment_url":
			out.PaymentURL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto10(out *jwriter.Writer, in CreatePaymentResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"payment_url\":"
		out.RawString(prefix[1:])
		out.String(string(in.PaymentURL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreatePaymentResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreatePaymentResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreatePaymentResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreatePaymentResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto10(l, v)
}
func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto11(in *jlexer.Lexer, out *CreatePaymentRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "amount":
			out.Amount = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto11(out *jwriter.Writer, in CreatePaymentRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"amount\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Amount))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreatePaymentRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreatePaymentRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreatePaymentRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreatePaymentRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto11(l, v)
}
func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto12(in *jlexer.Lexer, out *BalanceResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "balance":
			out.Balance = int64(in.Int64())
		case "saved_payment_method_id":
			out.SavedPaymentMethodID = string(in.String())
		case "saved_payment_method_title":
			out.SavedPaymentMethodTitle = string(in.String())
		case "delivery_alert":
			if in.IsNull() {
				in.Skip()
				out.DeliveryAlert = nil
			} else {
				if out.DeliveryAlert == nil {
					out.DeliveryAlert = new(DeliveryAlertResponse)
				}
				(*out.DeliveryAlert).UnmarshalEasyJSON(in)
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto12(out *jwriter.Writer, in BalanceResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Balance))
	}
	if in.SavedPaymentMethodID != "" {
		const prefix string = ",\"saved_payment_method_id\":"
		out.RawString(prefix)
		out.String(string(in.SavedPaymentMethodID))
	}
	if in.SavedPaymentMethodTitle != "" {
		const prefix string = ",\"saved_payment_method_title\":"
		out.RawString(prefix)
		out.String(string(in.SavedPaymentMethodTitle))
	}
	if in.DeliveryAlert != nil {
		const prefix string = ",\"delivery_alert\":"
		out.RawString(prefix)
		(*in.DeliveryAlert).MarshalEasyJSON(out)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v BalanceResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v BalanceResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *BalanceResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *BalanceResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto12(l, v)
}
func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto13(in *jlexer.Lexer, out *AutopaySettingsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "enabled":
			out.Enabled = bool(in.Bool())
		case "threshold":
			out.Threshold = int64(in.Int64())
		case "limit":
			out.Limit = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto13(out *jwriter.Writer, in AutopaySettingsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"enabled\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Enabled))
	}
	{
		const prefix string = ",\"threshold\":"
		out.RawString(prefix)
		out.Int64(int64(in.Threshold))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AutopaySettingsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AutopaySettingsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AutopaySettingsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AutopaySettingsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto13(l, v)
}
func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto14(in *jlexer.Lexer, out *AutopaySettingsRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "enabled":
			out.Enabled = bool(in.Bool())
		case "threshold":
			out.Threshold = int64(in.Int64())
		case "limit":
			out.Limit = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto14(out *jwriter.Writer, in AutopaySettingsRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"enabled\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Enabled))
	}
	{
		const prefix string = ",\"threshold\":"
		out.RawString(prefix)
		out.Int64(int64(in.Threshold))
	}
	{
		const prefix string = ",\"limit\":"
		out.RawString(prefix)
		out.Int64(int64(in.Limit))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AutopaySettingsRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto14(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AutopaySettingsRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto14(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AutopaySettingsRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto14(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AutopaySettingsRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto14(l, v)
}
func easyjson94f0a767DecodeEshkereInternalHandlerV1Dto15(in *jlexer.Lexer, out *AdvertiserProfileResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "surname":
			out.Surname = string(in.String())
		case "email":
			out.Email = string(in.String())
		case "phone":
			out.Phone = string(in.String())
		case "avatar_url":
			out.AvatarURL = string(in.String())
		case "balance":
			out.Balance = int64(in.Int64())
		case "company":
			out.Company = string(in.String())
		case "city":
			out.City = string(in.String())
		case "tariff":
			out.Tariff = string(in.String())
		case "role":
			out.Role = string(in.String())
		case "created_at":
			out.CreatedAt = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson94f0a767EncodeEshkereInternalHandlerV1Dto15(out *jwriter.Writer, in AdvertiserProfileResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"surname\":"
		out.RawString(prefix)
		out.String(string(in.Surname))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	if in.AvatarURL != "" {
		const prefix string = ",\"avatar_url\":"
		out.RawString(prefix)
		out.String(string(in.AvatarURL))
	}
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix)
		out.Int64(int64(in.Balance))
	}
	{
		const prefix string = ",\"company\":"
		out.RawString(prefix)
		out.String(string(in.Company))
	}
	{
		const prefix string = ",\"city\":"
		out.RawString(prefix)
		out.String(string(in.City))
	}
	{
		const prefix string = ",\"tariff\":"
		out.RawString(prefix)
		out.String(string(in.Tariff))
	}
	{
		const prefix string = ",\"role\":"
		out.RawString(prefix)
		out.String(string(in.Role))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdvertiserProfileResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto15(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdvertiserProfileResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson94f0a767EncodeEshkereInternalHandlerV1Dto15(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdvertiserProfileResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto15(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdvertiserProfileResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson94f0a767DecodeEshkereInternalHandlerV1Dto15(l, v)
}
