// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson531be4a9DecodeEshkereInternalHandlerV1Dto(in *jlexer.Lexer, out *ListAppealsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "advertiser_id":
			out.AdvertiserID = int(in.Int())
		case "appeals":
			if in.IsNull() {
				in.Skip()
				out.Appeals = nil
			} else {
				in.Delim('[')
				if out.Appeals == nil {
					if !in.IsDelim(']') {
						out.Appeals = make([]*AppealResponse, 0, 8)
					} else {
						out.Appeals = []*AppealResponse{}
					}
				} else {
					out.Appeals = (out.Appeals)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *AppealResponse
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(AppealResponse)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.Appeals = append(out.Appeals, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson531be4a9EncodeEshkereInternalHandlerV1Dto(out *jwriter.Writer, in ListAppealsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"advertiser_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.AdvertiserID))
	}
	{
		const prefix string = ",\"appeals\":"
		out.RawString(prefix)
		if in.Appeals == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Appeals {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListAppealsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson531be4a9EncodeEshkereInternalHandlerV1Dto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListAppealsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson531be4a9EncodeEshkereInternalHandlerV1Dto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListAppealsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson531be4a9DecodeEshkereInternalHandlerV1Dto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListAppealsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson531be4a9DecodeEshkereInternalHandlerV1Dto(l, v)
}
func easyjson531be4a9DecodeEshkereInternalHandlerV1Dto1(in *jlexer.Lexer, out *CreateAppealResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson531be4a9EncodeEshkereInternalHandlerV1Dto1(out *jwriter.Writer, in CreateAppealResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateAppealResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson531be4a9EncodeEshkereInternalHandlerV1Dto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateAppealResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson531be4a9EncodeEshkereInternalHandlerV1Dto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateAppealResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson531be4a9DecodeEshkereInternalHandlerV1Dto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateAppealResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson531be4a9DecodeEshkereInternalHandlerV1Dto1(l, v)
}
func easyjson531be4a9DecodeEshkereInternalHandlerV1Dto2(in *jlexer.Lexer, out *CreateAppealRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "category":
			out.Category = string(in.String())
		case "title":
			out.Title = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "name":
			out.Name = string(in.String())
		case "email":
			out.Email = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson531be4a9EncodeEshkereInternalHandlerV1Dto2(out *jwriter.Writer, in CreateAppealRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix[1:])
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreateAppealRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson531be4a9EncodeEshkereInternalHandlerV1Dto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreateAppealRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson531be4a9EncodeEshkereInternalHandlerV1Dto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreateAppealRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson531be4a9DecodeEshkereInternalHandlerV1Dto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreateAppealRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson531be4a9DecodeEshkereInternalHandlerV1Dto2(l, v)
}
func easyjson531be4a9DecodeEshkereInternalHandlerV1Dto3(in *jlexer.Lexer, out *AppealResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "status":
			out.Status = string(in.String())
		case "category":
			out.Category = string(in.String())
		case "title":
			out.Title = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "image_url":
			out.ImageURL = string(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson531be4a9EncodeEshkereInternalHandlerV1Dto3(out *jwriter.Writer, in AppealResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"category\":"
		out.RawString(prefix)
		out.String(string(in.Category))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	if in.ImageURL != "" {
		const prefix string = ",\"image_url\":"
		out.RawString(prefix)
		out.String(string(in.ImageURL))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AppealResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson531be4a9EncodeEshkereInternalHandlerV1Dto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AppealResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson531be4a9EncodeEshkereInternalHandlerV1Dto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AppealResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson531be4a9DecodeEshkereInternalHandlerV1Dto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AppealResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson531be4a9DecodeEshkereInternalHandlerV1Dto3(l, v)
}
