// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto(in *jlexer.Lexer, out *UpdatePartnerBlockSelfAdRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "reserved":
			out.Reserved = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto(out *jwriter.Writer, in UpdatePartnerBlockSelfAdRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"reserved\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Reserved))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdatePartnerBlockSelfAdRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdatePartnerBlockSelfAdRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdatePartnerBlockSelfAdRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdatePartnerBlockSelfAdRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto(l, v)
}
func easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto1(in *jlexer.Lexer, out *UpdatePartnerBlockMetaRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "name":
			if in.IsNull() {
				in.Skip()
				out.Name = nil
			} else {
				if out.Name == nil {
					out.Name = new(string)
				}
				*out.Name = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
				out.Status = nil
			} else {
				if out.Status == nil {
					out.Status = new(string)
				}
				*out.Status = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto1(out *jwriter.Writer, in UpdatePartnerBlockMetaRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix[1:])
		if in.Name == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Name))
		}
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		if in.Status == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Status))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdatePartnerBlockMetaRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdatePartnerBlockMetaRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdatePartnerBlockMetaRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdatePartnerBlockMetaRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto1(l, v)
}
func easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto2(in *jlexer.Lexer, out *UpdatePartnerBlockGeographyRuleRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "geo_code":
			out.GeoCode = string(in.String())
		case "is_enabled":
			out.IsEnabled = bool(in.Bool())
		case "cpmv":
			if in.IsNull() {
				in.Skip()
				out.CPMV = nil
			} else {
				if out.CPMV == nil {
					out.CPMV = new(int64)
				}
				*out.CPMV = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto2(out *jwriter.Writer, in UpdatePartnerBlockGeographyRuleRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"geo_code\":"
		out.RawString(prefix[1:])
		out.String(string(in.GeoCode))
	}
	{
		const prefix string = ",\"is_enabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsEnabled))
	}
	{
		const prefix string = ",\"cpmv\":"
		out.RawString(prefix)
		if in.CPMV == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.CPMV))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdatePartnerBlockGeographyRuleRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdatePartnerBlockGeographyRuleRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdatePartnerBlockGeographyRuleRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdatePartnerBlockGeographyRuleRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto2(l, v)
}
func easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto3(in *jlexer.Lexer, out *UpdatePartnerBlockGeographyRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "only_configured":
			out.OnlyConfigured = bool(in.Bool())
		case "global_cpmv":
			if in.IsNull() {
				in.Skip()
				out.GlobalCPMV = nil
			} else {
				if out.GlobalCPMV == nil {
					out.GlobalCPMV = new(int64)
				}
				*out.GlobalCPMV = int64(in.Int64())
			}
		case "rules":
			if in.IsNull() {
				in.Skip()
				out.Rules = nil
			} else {
				in.Delim('[')
				if out.Rules == nil {
					if !in.IsDelim(']') {
						out.Rules = make([]UpdatePartnerBlockGeographyRuleRequest, 0, 2)
					} else {
						out.Rules = []UpdatePartnerBlockGeographyRuleRequest{}
					}
				} else {
					out.Rules = (out.Rules)[:0]
				}
				for !in.IsDelim(']') {
					var v1 UpdatePartnerBlockGeographyRuleRequest
					(v1).UnmarshalEasyJSON(in)
					out.Rules = append(out.Rules, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto3(out *jwriter.Writer, in UpdatePartnerBlockGeographyRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"only_configured\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.OnlyConfigured))
	}
	{
		const prefix string = ",\"global_cpmv\":"
		out.RawString(prefix)
		if in.GlobalCPMV == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.GlobalCPMV))
		}
	}
	{
		const prefix string = ",\"rules\":"
		out.RawString(prefix)
		if in.Rules == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Rules {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdatePartnerBlockGeographyRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdatePartnerBlockGeographyRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdatePartnerBlockGeographyRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdatePartnerBlockGeographyRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto3(l, v)
}
func easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto4(in *jlexer.Lexer, out *UpdatePartnerBlockGeneralRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "cpm_strategy":
			if in.IsNull() {
				in.Skip()
				out.CPMStrategy = nil
			} else {
				if out.CPMStrategy == nil {
					out.CPMStrategy = new(string)
				}
				*out.CPMStrategy = string(in.String())
			}
		case "amp_mode":
			if in.IsNull() {
				in.Skip()
				out.AmpMode = nil
			} else {
				if out.AmpMode == nil {
					out.AmpMode = new(string)
				}
				*out.AmpMode = string(in.String())
			}
		case "size_mode":
			if in.IsNull() {
				in.Skip()
				out.SizeMode = nil
			} else {
				if out.SizeMode == nil {
					out.SizeMode = new(string)
				}
				*out.SizeMode = string(in.String())
			}
		case "border_mode":
			if in.IsNull() {
				in.Skip()
				out.BorderMode = nil
			} else {
				if out.BorderMode == nil {
					out.BorderMode = new(string)
				}
				*out.BorderMode = string(in.String())
			}
		case "corner_mode":
			if in.IsNull() {
				in.Skip()
				out.CornerMode = nil
			} else {
				if out.CornerMode == nil {
					out.CornerMode = new(string)
				}
				*out.CornerMode = string(in.String())
			}
		case "theme":
			if in.IsNull() {
				in.Skip()
				out.Theme = nil
			} else {
				if out.Theme == nil {
					out.Theme = new(string)
				}
				*out.Theme = string(in.String())
			}
		case "interscroller_mode":
			if in.IsNull() {
				in.Skip()
				out.InterscrollerMode = nil
			} else {
				if out.InterscrollerMode == nil {
					out.InterscrollerMode = new(string)
				}
				*out.InterscrollerMode = string(in.String())
			}
		case "interscroller_background_color":
			if in.IsNull() {
				in.Skip()
				out.InterscrollerBackgroundColor = nil
			} else {
				if out.InterscrollerBackgroundColor == nil {
					out.InterscrollerBackgroundColor = new(string)
				}
				*out.InterscrollerBackgroundColor = string(in.String())
			}
		case "revenue_share_bps":
			if in.IsNull() {
				in.Skip()
				out.RevenueShareBPS = nil
			} else {
				if out.RevenueShareBPS == nil {
					out.RevenueShareBPS = new(int)
				}
				*out.RevenueShareBPS = int(in.Int())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto4(out *jwriter.Writer, in UpdatePartnerBlockGeneralRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cpm_strategy\":"
		out.RawString(prefix[1:])
		if in.CPMStrategy == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.CPMStrategy))
		}
	}
	{
		const prefix string = ",\"amp_mode\":"
		out.RawString(prefix)
		if in.AmpMode == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.AmpMode))
		}
	}
	{
		const prefix string = ",\"size_mode\":"
		out.RawString(prefix)
		if in.SizeMode == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.SizeMode))
		}
	}
	{
		const prefix string = ",\"border_mode\":"
		out.RawString(prefix)
		if in.BorderMode == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.BorderMode))
		}
	}
	{
		const prefix string = ",\"corner_mode\":"
		out.RawString(prefix)
		if in.CornerMode == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.CornerMode))
		}
	}
	{
		const prefix string = ",\"theme\":"
		out.RawString(prefix)
		if in.Theme == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Theme))
		}
	}
	{
		const prefix string = ",\"interscroller_mode\":"
		out.RawString(prefix)
		if in.InterscrollerMode == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.InterscrollerMode))
		}
	}
	{
		const prefix string = ",\"interscroller_background_color\":"
		out.RawString(prefix)
		if in.InterscrollerBackgroundColor == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.InterscrollerBackgroundColor))
		}
	}
	{
		const prefix string = ",\"revenue_share_bps\":"
		out.RawString(prefix)
		if in.RevenueShareBPS == nil {
			out.RawString("null")
		} else {
			out.Int(int(*in.RevenueShareBPS))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdatePartnerBlockGeneralRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdatePartnerBlockGeneralRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdatePartnerBlockGeneralRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdatePartnerBlockGeneralRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto4(l, v)
}
func easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto5(in *jlexer.Lexer, out *PartnerBlockSelfAdSettingsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "reserved":
			out.Reserved = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto5(out *jwriter.Writer, in PartnerBlockSelfAdSettingsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"reserved\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.Reserved))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartnerBlockSelfAdSettingsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartnerBlockSelfAdSettingsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartnerBlockSelfAdSettingsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartnerBlockSelfAdSettingsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto5(l, v)
}
func easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto6(in *jlexer.Lexer, out *PartnerBlockResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "block_type":
			out.BlockType = string(in.String())
		case "status":
			out.Status = string(in.String())
		case "created_at":
			out.CreatedAt = string(in.String())
		case "updated_at":
			out.UpdatedAt = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto6(out *jwriter.Writer, in PartnerBlockResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"block_type\":"
		out.RawString(prefix)
		out.String(string(in.BlockType))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	if in.UpdatedAt != "" {
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.String(string(in.UpdatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartnerBlockResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartnerBlockResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartnerBlockResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartnerBlockResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto6(l, v)
}
func easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto7(in *jlexer.Lexer, out *PartnerBlockGeographySettingsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "only_configured":
			out.OnlyConfigured = bool(in.Bool())
		case "global_cpmv":
			if in.IsNull() {
				in.Skip()
				out.GlobalCPMV = nil
			} else {
				if out.GlobalCPMV == nil {
					out.GlobalCPMV = new(int64)
				}
				*out.GlobalCPMV = int64(in.Int64())
			}
		case "rules":
			if in.IsNull() {
				in.Skip()
				out.Rules = nil
			} else {
				in.Delim('[')
				if out.Rules == nil {
					if !in.IsDelim(']') {
						out.Rules = make([]*PartnerBlockGeoRuleResponse, 0, 8)
					} else {
						out.Rules = []*PartnerBlockGeoRuleResponse{}
					}
				} else {
					out.Rules = (out.Rules)[:0]
				}
				for !in.IsDelim(']') {
					var v4 *PartnerBlockGeoRuleResponse
					if in.IsNull() {
						in.Skip()
						v4 = nil
					} else {
						if v4 == nil {
							v4 = new(PartnerBlockGeoRuleResponse)
						}
						(*v4).UnmarshalEasyJSON(in)
					}
					out.Rules = append(out.Rules, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto7(out *jwriter.Writer, in PartnerBlockGeographySettingsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"only_configured\":"
		out.RawString(prefix[1:])
		out.Bool(bool(in.OnlyConfigured))
	}
	{
		const prefix string = ",\"global_cpmv\":"
		out.RawString(prefix)
		if in.GlobalCPMV == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.GlobalCPMV))
		}
	}
	{
		const prefix string = ",\"rules\":"
		out.RawString(prefix)
		if in.Rules == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Rules {
				if v5 > 0 {
					out.RawByte(',')
				}
				if v6 == nil {
					out.RawString("null")
				} else {
					(*v6).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartnerBlockGeographySettingsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartnerBlockGeographySettingsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartnerBlockGeographySettingsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartnerBlockGeographySettingsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto7(l, v)
}
func easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto8(in *jlexer.Lexer, out *PartnerBlockGeoRuleResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "geo_code":
			out.GeoCode = string(in.String())
		case "is_enabled":
			out.IsEnabled = bool(in.Bool())
		case "cpmv":
			if in.IsNull() {
				in.Skip()
				out.CPMV = nil
			} else {
				if out.CPMV == nil {
					out.CPMV = new(int64)
				}
				*out.CPMV = int64(in.Int64())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto8(out *jwriter.Writer, in PartnerBlockGeoRuleResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"geo_code\":"
		out.RawString(prefix[1:])
		out.String(string(in.GeoCode))
	}
	{
		const prefix string = ",\"is_enabled\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsEnabled))
	}
	{
		const prefix string = ",\"cpmv\":"
		out.RawString(prefix)
		if in.CPMV == nil {
			out.RawString("null")
		} else {
			out.Int64(int64(*in.CPMV))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartnerBlockGeoRuleResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartnerBlockGeoRuleResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartnerBlockGeoRuleResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartnerBlockGeoRuleResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto8(l, v)
}
func easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto9(in *jlexer.Lexer, out *PartnerBlockGeneralSettingsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "cpm_strategy":
			out.CPMStrategy = string(in.String())
		case "amp_mode":
			out.AmpMode = string(in.String())
		case "size_mode":
			out.SizeMode = string(in.String())
		case "border_mode":
			out.BorderMode = string(in.String())
		case "corner_mode":
			out.CornerMode = string(in.String())
		case "theme":
			out.Theme = string(in.String())
		case "interscroller_mode":
			out.InterscrollerMode = string(in.String())
		case "interscroller_background_color":
			if in.IsNull() {
				in.Skip()
				out.InterscrollerBackgroundColor = nil
			} else {
				if out.InterscrollerBackgroundColor == nil {
					out.InterscrollerBackgroundColor = new(string)
				}
				*out.InterscrollerBackgroundColor = string(in.String())
			}
		case "revenue_share_bps":
			out.RevenueShareBPS = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto9(out *jwriter.Writer, in PartnerBlockGeneralSettingsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"cpm_strategy\":"
		out.RawString(prefix[1:])
		out.String(string(in.CPMStrategy))
	}
	{
		const prefix string = ",\"amp_mode\":"
		out.RawString(prefix)
		out.String(string(in.AmpMode))
	}
	{
		const prefix string = ",\"size_mode\":"
		out.RawString(prefix)
		out.String(string(in.SizeMode))
	}
	{
		const prefix string = ",\"border_mode\":"
		out.RawString(prefix)
		out.String(string(in.BorderMode))
	}
	{
		const prefix string = ",\"corner_mode\":"
		out.RawString(prefix)
		out.String(string(in.CornerMode))
	}
	{
		const prefix string = ",\"theme\":"
		out.RawString(prefix)
		out.String(string(in.Theme))
	}
	{
		const prefix string = ",\"interscroller_mode\":"
		out.RawString(prefix)
		out.String(string(in.InterscrollerMode))
	}
	{
		const prefix string = ",\"interscroller_background_color\":"
		out.RawString(prefix)
		if in.InterscrollerBackgroundColor == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.InterscrollerBackgroundColor))
		}
	}
	{
		const prefix string = ",\"revenue_share_bps\":"
		out.RawString(prefix)
		out.Int(int(in.RevenueShareBPS))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartnerBlockGeneralSettingsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartnerBlockGeneralSettingsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartnerBlockGeneralSettingsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartnerBlockGeneralSettingsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto9(l, v)
}
func easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto10(in *jlexer.Lexer, out *PartnerBlockEmbedResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "embed_token":
			out.EmbedToken = string(in.String())
		case "html_snippet":
			out.HTMLSnippet = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto10(out *jwriter.Writer, in PartnerBlockEmbedResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"embed_token\":"
		out.RawString(prefix[1:])
		out.String(string(in.EmbedToken))
	}
	{
		const prefix string = ",\"html_snippet\":"
		out.RawString(prefix)
		out.String(string(in.HTMLSnippet))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartnerBlockEmbedResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto10(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartnerBlockEmbedResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto10(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartnerBlockEmbedResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto10(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartnerBlockEmbedResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto10(l, v)
}
func easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto11(in *jlexer.Lexer, out *PartnerBlockDetailsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "site_id":
			out.SiteID = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "block_type":
			out.BlockType = string(in.String())
		case "status":
			out.Status = string(in.String())
		case "supported_platforms":
			if in.IsNull() {
				in.Skip()
				out.SupportedPlatforms = nil
			} else {
				in.Delim('[')
				if out.SupportedPlatforms == nil {
					if !in.IsDelim(']') {
						out.SupportedPlatforms = make([]string, 0, 4)
					} else {
						out.SupportedPlatforms = []string{}
					}
				} else {
					out.SupportedPlatforms = (out.SupportedPlatforms)[:0]
				}
				for !in.IsDelim(']') {
					var v7 string
					v7 = string(in.String())
					out.SupportedPlatforms = append(out.SupportedPlatforms, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "general_settings":
			(out.GeneralSettings).UnmarshalEasyJSON(in)
		case "geography_settings":
			(out.GeographySettings).UnmarshalEasyJSON(in)
		case "self_ad_settings":
			(out.SelfAdSettings).UnmarshalEasyJSON(in)
		case "created_at":
			out.CreatedAt = string(in.String())
		case "updated_at":
			out.UpdatedAt = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto11(out *jwriter.Writer, in PartnerBlockDetailsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"site_id\":"
		out.RawString(prefix)
		out.Int(int(in.SiteID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"block_type\":"
		out.RawString(prefix)
		out.String(string(in.BlockType))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"supported_platforms\":"
		out.RawString(prefix)
		if in.SupportedPlatforms == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.SupportedPlatforms {
				if v8 > 0 {
					out.RawByte(',')
				}
				out.String(string(v9))
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"general_settings\":"
		out.RawString(prefix)
		(in.GeneralSettings).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"geography_settings\":"
		out.RawString(prefix)
		(in.GeographySettings).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"self_ad_settings\":"
		out.RawString(prefix)
		(in.SelfAdSettings).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	if in.UpdatedAt != "" {
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.String(string(in.UpdatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartnerBlockDetailsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto11(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartnerBlockDetailsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto11(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartnerBlockDetailsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto11(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartnerBlockDetailsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto11(l, v)
}
func easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto12(in *jlexer.Lexer, out *ListPartnerBlocksResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "site_id":
			out.SiteID = int(in.Int())
		case "blocks":
			if in.IsNull() {
				in.Skip()
				out.Blocks = nil
			} else {
				in.Delim('[')
				if out.Blocks == nil {
					if !in.IsDelim(']') {
						out.Blocks = make([]*PartnerBlockResponse, 0, 8)
					} else {
						out.Blocks = []*PartnerBlockResponse{}
					}
				} else {
					out.Blocks = (out.Blocks)[:0]
				}
				for !in.IsDelim(']') {
					var v10 *PartnerBlockResponse
					if in.IsNull() {
						in.Skip()
						v10 = nil
					} else {
						if v10 == nil {
							v10 = new(PartnerBlockResponse)
						}
						(*v10).UnmarshalEasyJSON(in)
					}
					out.Blocks = append(out.Blocks, v10)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto12(out *jwriter.Writer, in ListPartnerBlocksResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"site_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.SiteID))
	}
	{
		const prefix string = ",\"blocks\":"
		out.RawString(prefix)
		if in.Blocks == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v11, v12 := range in.Blocks {
				if v11 > 0 {
					out.RawByte(',')
				}
				if v12 == nil {
					out.RawString("null")
				} else {
					(*v12).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListPartnerBlocksResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto12(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListPartnerBlocksResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto12(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListPartnerBlocksResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto12(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListPartnerBlocksResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto12(l, v)
}
func easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto13(in *jlexer.Lexer, out *CreatePartnerBlockRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "block_type":
			out.BlockType = string(in.String())
		case "name":
			out.Name = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto13(out *jwriter.Writer, in CreatePartnerBlockRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"block_type\":"
		out.RawString(prefix[1:])
		out.String(string(in.BlockType))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreatePartnerBlockRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto13(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreatePartnerBlockRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonEe7e678eEncodeEshkereInternalHandlerV1Dto13(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreatePartnerBlockRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto13(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreatePartnerBlockRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonEe7e678eDecodeEshkereInternalHandlerV1Dto13(l, v)
}
