// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson5a03660cDecodeEshkereInternalHandlerV1Dto(in *jlexer.Lexer, out *UpdatePartnerProfileRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "last_name":
			if in.IsNull() {
				in.Skip()
				out.LastName = nil
			} else {
				if out.LastName == nil {
					out.LastName = new(string)
				}
				*out.LastName = string(in.String())
			}
		case "first_name":
			if in.IsNull() {
				in.Skip()
				out.FirstName = nil
			} else {
				if out.FirstName == nil {
					out.FirstName = new(string)
				}
				*out.FirstName = string(in.String())
			}
		case "middle_name":
			if in.IsNull() {
				in.Skip()
				out.MiddleName = nil
			} else {
				if out.MiddleName == nil {
					out.MiddleName = new(string)
				}
				*out.MiddleName = string(in.String())
			}
		case "birth_date":
			if in.IsNull() {
				in.Skip()
				out.BirthDate = nil
			} else {
				if out.BirthDate == nil {
					out.BirthDate = new(string)
				}
				*out.BirthDate = string(in.String())
			}
		case "email":
			if in.IsNull() {
				in.Skip()
				out.Email = nil
			} else {
				if out.Email == nil {
					out.Email = new(string)
				}
				*out.Email = string(in.String())
			}
		case "phone":
			if in.IsNull() {
				in.Skip()
				out.Phone = nil
			} else {
				if out.Phone == nil {
					out.Phone = new(string)
				}
				*out.Phone = string(in.String())
			}
		case "country_code":
			if in.IsNull() {
				in.Skip()
				out.CountryCode = nil
			} else {
				if out.CountryCode == nil {
					out.CountryCode = new(string)
				}
				*out.CountryCode = string(in.String())
			}
		case "registration_region_code":
			if in.IsNull() {
				in.Skip()
				out.RegistrationRegionCode = nil
			} else {
				if out.RegistrationRegionCode == nil {
					out.RegistrationRegionCode = new(string)
				}
				*out.RegistrationRegionCode = string(in.String())
			}
		case "cooperation_form":
			if in.IsNull() {
				in.Skip()
				out.CooperationForm = nil
			} else {
				if out.CooperationForm == nil {
					out.CooperationForm = new(string)
				}
				*out.CooperationForm = string(in.String())
			}
		case "payout_currency":
			if in.IsNull() {
				in.Skip()
				out.PayoutCurrency = nil
			} else {
				if out.PayoutCurrency == nil {
					out.PayoutCurrency = new(string)
				}
				*out.PayoutCurrency = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a03660cEncodeEshkereInternalHandlerV1Dto(out *jwriter.Writer, in UpdatePartnerProfileRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"last_name\":"
		out.RawString(prefix[1:])
		if in.LastName == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.LastName))
		}
	}
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix)
		if in.FirstName == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.FirstName))
		}
	}
	{
		const prefix string = ",\"middle_name\":"
		out.RawString(prefix)
		if in.MiddleName == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.MiddleName))
		}
	}
	{
		const prefix string = ",\"birth_date\":"
		out.RawString(prefix)
		if in.BirthDate == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.BirthDate))
		}
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		if in.Email == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Email))
		}
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		if in.Phone == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Phone))
		}
	}
	{
		const prefix string = ",\"country_code\":"
		out.RawString(prefix)
		if in.CountryCode == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.CountryCode))
		}
	}
	{
		const prefix string = ",\"registration_region_code\":"
		out.RawString(prefix)
		if in.RegistrationRegionCode == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.RegistrationRegionCode))
		}
	}
	{
		const prefix string = ",\"cooperation_form\":"
		out.RawString(prefix)
		if in.CooperationForm == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.CooperationForm))
		}
	}
	{
		const prefix string = ",\"payout_currency\":"
		out.RawString(prefix)
		if in.PayoutCurrency == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.PayoutCurrency))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdatePartnerProfileRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5a03660cEncodeEshkereInternalHandlerV1Dto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdatePartnerProfileRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5a03660cEncodeEshkereInternalHandlerV1Dto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdatePartnerProfileRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5a03660cDecodeEshkereInternalHandlerV1Dto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdatePartnerProfileRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5a03660cDecodeEshkereInternalHandlerV1Dto(l, v)
}
func easyjson5a03660cDecodeEshkereInternalHandlerV1Dto1(in *jlexer.Lexer, out *PartnerRegisterRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "last_name":
			out.LastName = string(in.String())
		case "first_name":
			out.FirstName = string(in.String())
		case "middle_name":
			out.MiddleName = string(in.String())
		case "birth_date":
			out.BirthDate = string(in.String())
		case "email":
			out.Email = string(in.String())
		case "phone":
			out.Phone = string(in.String())
		case "country_code":
			out.CountryCode = string(in.String())
		case "registration_region_code":
			out.RegistrationRegionCode = string(in.String())
		case "cooperation_form":
			out.CooperationForm = string(in.String())
		case "payout_currency":
			out.PayoutCurrency = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a03660cEncodeEshkereInternalHandlerV1Dto1(out *jwriter.Writer, in PartnerRegisterRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"last_name\":"
		out.RawString(prefix[1:])
		out.String(string(in.LastName))
	}
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"middle_name\":"
		out.RawString(prefix)
		out.String(string(in.MiddleName))
	}
	{
		const prefix string = ",\"birth_date\":"
		out.RawString(prefix)
		out.String(string(in.BirthDate))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	{
		const prefix string = ",\"country_code\":"
		out.RawString(prefix)
		out.String(string(in.CountryCode))
	}
	{
		const prefix string = ",\"registration_region_code\":"
		out.RawString(prefix)
		out.String(string(in.RegistrationRegionCode))
	}
	{
		const prefix string = ",\"cooperation_form\":"
		out.RawString(prefix)
		out.String(string(in.CooperationForm))
	}
	{
		const prefix string = ",\"payout_currency\":"
		out.RawString(prefix)
		out.String(string(in.PayoutCurrency))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartnerRegisterRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5a03660cEncodeEshkereInternalHandlerV1Dto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartnerRegisterRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5a03660cEncodeEshkereInternalHandlerV1Dto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartnerRegisterRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5a03660cDecodeEshkereInternalHandlerV1Dto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartnerRegisterRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5a03660cDecodeEshkereInternalHandlerV1Dto1(l, v)
}
func easyjson5a03660cDecodeEshkereInternalHandlerV1Dto2(in *jlexer.Lexer, out *PartnerProfileResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "last_name":
			out.LastName = string(in.String())
		case "first_name":
			out.FirstName = string(in.String())
		case "middle_name":
			out.MiddleName = string(in.String())
		case "birth_date":
			out.BirthDate = string(in.String())
		case "email":
			out.Email = string(in.String())
		case "phone":
			out.Phone = string(in.String())
		case "country_code":
			out.CountryCode = string(in.String())
		case "registration_region_code":
			out.RegistrationRegionCode = string(in.String())
		case "cooperation_form":
			out.CooperationForm = string(in.String())
		case "payout_currency":
			out.PayoutCurrency = string(in.String())
		case "balance":
			out.Balance = int64(in.Int64())
		case "created_at":
			out.CreatedAt = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a03660cEncodeEshkereInternalHandlerV1Dto2(out *jwriter.Writer, in PartnerProfileResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"last_name\":"
		out.RawString(prefix)
		out.String(string(in.LastName))
	}
	{
		const prefix string = ",\"first_name\":"
		out.RawString(prefix)
		out.String(string(in.FirstName))
	}
	{
		const prefix string = ",\"middle_name\":"
		out.RawString(prefix)
		out.String(string(in.MiddleName))
	}
	{
		const prefix string = ",\"birth_date\":"
		out.RawString(prefix)
		out.String(string(in.BirthDate))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	{
		const prefix string = ",\"country_code\":"
		out.RawString(prefix)
		out.String(string(in.CountryCode))
	}
	{
		const prefix string = ",\"registration_region_code\":"
		out.RawString(prefix)
		out.String(string(in.RegistrationRegionCode))
	}
	{
		const prefix string = ",\"cooperation_form\":"
		out.RawString(prefix)
		out.String(string(in.CooperationForm))
	}
	{
		const prefix string = ",\"payout_currency\":"
		out.RawString(prefix)
		out.String(string(in.PayoutCurrency))
	}
	{
		const prefix string = ",\"balance\":"
		out.RawString(prefix)
		out.Int64(int64(in.Balance))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartnerProfileResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5a03660cEncodeEshkereInternalHandlerV1Dto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartnerProfileResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5a03660cEncodeEshkereInternalHandlerV1Dto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartnerProfileResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5a03660cDecodeEshkereInternalHandlerV1Dto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartnerProfileResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5a03660cDecodeEshkereInternalHandlerV1Dto2(l, v)
}
func easyjson5a03660cDecodeEshkereInternalHandlerV1Dto3(in *jlexer.Lexer, out *PartnerLoginRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "identifier":
			out.Identifier = string(in.String())
		case "password":
			out.Password = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a03660cEncodeEshkereInternalHandlerV1Dto3(out *jwriter.Writer, in PartnerLoginRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"identifier\":"
		out.RawString(prefix[1:])
		out.String(string(in.Identifier))
	}
	{
		const prefix string = ",\"password\":"
		out.RawString(prefix)
		out.String(string(in.Password))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartnerLoginRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5a03660cEncodeEshkereInternalHandlerV1Dto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartnerLoginRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5a03660cEncodeEshkereInternalHandlerV1Dto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartnerLoginRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5a03660cDecodeEshkereInternalHandlerV1Dto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartnerLoginRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5a03660cDecodeEshkereInternalHandlerV1Dto3(l, v)
}
func easyjson5a03660cDecodeEshkereInternalHandlerV1Dto4(in *jlexer.Lexer, out *PartnerAuthResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "email":
			out.Email = string(in.String())
		case "phone":
			out.Phone = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson5a03660cEncodeEshkereInternalHandlerV1Dto4(out *jwriter.Writer, in PartnerAuthResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"email\":"
		out.RawString(prefix)
		out.String(string(in.Email))
	}
	{
		const prefix string = ",\"phone\":"
		out.RawString(prefix)
		out.String(string(in.Phone))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartnerAuthResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson5a03660cEncodeEshkereInternalHandlerV1Dto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartnerAuthResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson5a03660cEncodeEshkereInternalHandlerV1Dto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartnerAuthResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson5a03660cDecodeEshkereInternalHandlerV1Dto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartnerAuthResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson5a03660cDecodeEshkereInternalHandlerV1Dto4(l, v)
}
