// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson4cfab318DecodeEshkereInternalHandlerV1Dto(in *jlexer.Lexer, out *UpdatePartnerSiteRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "domain":
			if in.IsNull() {
				in.Skip()
				out.Domain = nil
			} else {
				if out.Domain == nil {
					out.Domain = new(string)
				}
				*out.Domain = string(in.String())
			}
		case "site_name":
			if in.IsNull() {
				in.Skip()
				out.SiteName = nil
			} else {
				if out.SiteName == nil {
					out.SiteName = new(string)
				}
				*out.SiteName = string(in.String())
			}
		case "status":
			if in.IsNull() {
				in.Skip()
				out.Status = nil
			} else {
				if out.Status == nil {
					out.Status = new(string)
				}
				*out.Status = string(in.String())
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4cfab318EncodeEshkereInternalHandlerV1Dto(out *jwriter.Writer, in UpdatePartnerSiteRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"domain\":"
		out.RawString(prefix[1:])
		if in.Domain == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Domain))
		}
	}
	{
		const prefix string = ",\"site_name\":"
		out.RawString(prefix)
		if in.SiteName == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.SiteName))
		}
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		if in.Status == nil {
			out.RawString("null")
		} else {
			out.String(string(*in.Status))
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UpdatePartnerSiteRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4cfab318EncodeEshkereInternalHandlerV1Dto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UpdatePartnerSiteRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4cfab318EncodeEshkereInternalHandlerV1Dto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UpdatePartnerSiteRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4cfab318DecodeEshkereInternalHandlerV1Dto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UpdatePartnerSiteRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4cfab318DecodeEshkereInternalHandlerV1Dto(l, v)
}
func easyjson4cfab318DecodeEshkereInternalHandlerV1Dto1(in *jlexer.Lexer, out *PartnerSiteResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "domain":
			out.Domain = string(in.String())
		case "site_name":
			out.SiteName = string(in.String())
		case "status":
			out.Status = string(in.String())
		case "created_at":
			out.CreatedAt = string(in.String())
		case "updated_at":
			out.UpdatedAt = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4cfab318EncodeEshkereInternalHandlerV1Dto1(out *jwriter.Writer, in PartnerSiteResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"domain\":"
		out.RawString(prefix)
		out.String(string(in.Domain))
	}
	{
		const prefix string = ",\"site_name\":"
		out.RawString(prefix)
		out.String(string(in.SiteName))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.String(string(in.CreatedAt))
	}
	if in.UpdatedAt != "" {
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.String(string(in.UpdatedAt))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartnerSiteResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4cfab318EncodeEshkereInternalHandlerV1Dto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartnerSiteResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4cfab318EncodeEshkereInternalHandlerV1Dto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartnerSiteResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4cfab318DecodeEshkereInternalHandlerV1Dto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartnerSiteResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4cfab318DecodeEshkereInternalHandlerV1Dto1(l, v)
}
func easyjson4cfab318DecodeEshkereInternalHandlerV1Dto2(in *jlexer.Lexer, out *ListPartnerSitesResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "partner_id":
			out.PartnerID = int(in.Int())
		case "sites":
			if in.IsNull() {
				in.Skip()
				out.Sites = nil
			} else {
				in.Delim('[')
				if out.Sites == nil {
					if !in.IsDelim(']') {
						out.Sites = make([]*PartnerSiteResponse, 0, 8)
					} else {
						out.Sites = []*PartnerSiteResponse{}
					}
				} else {
					out.Sites = (out.Sites)[:0]
				}
				for !in.IsDelim(']') {
					var v1 *PartnerSiteResponse
					if in.IsNull() {
						in.Skip()
						v1 = nil
					} else {
						if v1 == nil {
							v1 = new(PartnerSiteResponse)
						}
						(*v1).UnmarshalEasyJSON(in)
					}
					out.Sites = append(out.Sites, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4cfab318EncodeEshkereInternalHandlerV1Dto2(out *jwriter.Writer, in ListPartnerSitesResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"partner_id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.PartnerID))
	}
	{
		const prefix string = ",\"sites\":"
		out.RawString(prefix)
		if in.Sites == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Sites {
				if v2 > 0 {
					out.RawByte(',')
				}
				if v3 == nil {
					out.RawString("null")
				} else {
					(*v3).MarshalEasyJSON(out)
				}
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ListPartnerSitesResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4cfab318EncodeEshkereInternalHandlerV1Dto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ListPartnerSitesResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4cfab318EncodeEshkereInternalHandlerV1Dto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ListPartnerSitesResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4cfab318DecodeEshkereInternalHandlerV1Dto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ListPartnerSitesResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4cfab318DecodeEshkereInternalHandlerV1Dto2(l, v)
}
func easyjson4cfab318DecodeEshkereInternalHandlerV1Dto3(in *jlexer.Lexer, out *CreatePartnerSiteRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "domain":
			out.Domain = string(in.String())
		case "site_name":
			out.SiteName = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson4cfab318EncodeEshkereInternalHandlerV1Dto3(out *jwriter.Writer, in CreatePartnerSiteRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"domain\":"
		out.RawString(prefix[1:])
		out.String(string(in.Domain))
	}
	{
		const prefix string = ",\"site_name\":"
		out.RawString(prefix)
		out.String(string(in.SiteName))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CreatePartnerSiteRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson4cfab318EncodeEshkereInternalHandlerV1Dto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CreatePartnerSiteRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson4cfab318EncodeEshkereInternalHandlerV1Dto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CreatePartnerSiteRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson4cfab318DecodeEshkereInternalHandlerV1Dto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CreatePartnerSiteRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson4cfab318DecodeEshkereInternalHandlerV1Dto3(l, v)
}
