// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto(in *jlexer.Lexer, out *StatsUnavailableMetric) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "key":
			out.Key = string(in.String())
		case "label":
			out.Label = string(in.String())
		case "reason":
			out.Reason = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto(out *jwriter.Writer, in StatsUnavailableMetric) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"key\":"
		out.RawString(prefix[1:])
		out.String(string(in.Key))
	}
	{
		const prefix string = ",\"label\":"
		out.RawString(prefix)
		out.String(string(in.Label))
	}
	{
		const prefix string = ",\"reason\":"
		out.RawString(prefix)
		out.String(string(in.Reason))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatsUnavailableMetric) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatsUnavailableMetric) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatsUnavailableMetric) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatsUnavailableMetric) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto(l, v)
}
func easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto1(in *jlexer.Lexer, out *StatsPoint) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "date":
			out.Date = string(in.String())
		case "impressions":
			out.Impressions = int64(in.Int64())
		case "clicks":
			out.Clicks = int64(in.Int64())
		case "ctr":
			out.CTR = float64(in.Float64())
		case "spend":
			out.Spend = int64(in.Int64())
		case "cpc":
			out.CPC = float64(in.Float64())
		case "partner_reward":
			out.PartnerReward = int64(in.Int64())
		case "platform_revenue":
			out.PlatformRevenue = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto1(out *jwriter.Writer, in StatsPoint) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix[1:])
		out.String(string(in.Date))
	}
	{
		const prefix string = ",\"impressions\":"
		out.RawString(prefix)
		out.Int64(int64(in.Impressions))
	}
	{
		const prefix string = ",\"clicks\":"
		out.RawString(prefix)
		out.Int64(int64(in.Clicks))
	}
	{
		const prefix string = ",\"ctr\":"
		out.RawString(prefix)
		out.Float64(float64(in.CTR))
	}
	{
		const prefix string = ",\"spend\":"
		out.RawString(prefix)
		out.Int64(int64(in.Spend))
	}
	{
		const prefix string = ",\"cpc\":"
		out.RawString(prefix)
		out.Float64(float64(in.CPC))
	}
	{
		const prefix string = ",\"partner_reward\":"
		out.RawString(prefix)
		out.Int64(int64(in.PartnerReward))
	}
	{
		const prefix string = ",\"platform_revenue\":"
		out.RawString(prefix)
		out.Int64(int64(in.PlatformRevenue))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatsPoint) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatsPoint) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatsPoint) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatsPoint) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto1(l, v)
}
func easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto2(in *jlexer.Lexer, out *StatsPeriod) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "from":
			out.From = string(in.String())
		case "to":
			out.To = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto2(out *jwriter.Writer, in StatsPeriod) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix[1:])
		out.String(string(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatsPeriod) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatsPeriod) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatsPeriod) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatsPeriod) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto2(l, v)
}
func easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto3(in *jlexer.Lexer, out *StatsMetric) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "impressions":
			out.Impressions = int64(in.Int64())
		case "clicks":
			out.Clicks = int64(in.Int64())
		case "ctr":
			out.CTR = float64(in.Float64())
		case "spend":
			out.Spend = int64(in.Int64())
		case "cpc":
			out.CPC = float64(in.Float64())
		case "partner_reward":
			out.PartnerReward = int64(in.Int64())
		case "platform_revenue":
			out.PlatformRevenue = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto3(out *jwriter.Writer, in StatsMetric) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"impressions\":"
		out.RawString(prefix[1:])
		out.Int64(int64(in.Impressions))
	}
	{
		const prefix string = ",\"clicks\":"
		out.RawString(prefix)
		out.Int64(int64(in.Clicks))
	}
	{
		const prefix string = ",\"ctr\":"
		out.RawString(prefix)
		out.Float64(float64(in.CTR))
	}
	{
		const prefix string = ",\"spend\":"
		out.RawString(prefix)
		out.Int64(int64(in.Spend))
	}
	{
		const prefix string = ",\"cpc\":"
		out.RawString(prefix)
		out.Float64(float64(in.CPC))
	}
	{
		const prefix string = ",\"partner_reward\":"
		out.RawString(prefix)
		out.Int64(int64(in.PartnerReward))
	}
	{
		const prefix string = ",\"platform_revenue\":"
		out.RawString(prefix)
		out.Int64(int64(in.PlatformRevenue))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatsMetric) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatsMetric) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatsMetric) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatsMetric) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto3(l, v)
}
func easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto4(in *jlexer.Lexer, out *StatsEntityRow) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = int(in.Int())
		case "name":
			out.Name = string(in.String())
		case "impressions":
			out.Impressions = int64(in.Int64())
		case "clicks":
			out.Clicks = int64(in.Int64())
		case "ctr":
			out.CTR = float64(in.Float64())
		case "spend":
			out.Spend = int64(in.Int64())
		case "cpc":
			out.CPC = float64(in.Float64())
		case "partner_reward":
			out.PartnerReward = int64(in.Int64())
		case "platform_revenue":
			out.PlatformRevenue = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto4(out *jwriter.Writer, in StatsEntityRow) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Int(int(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	{
		const prefix string = ",\"impressions\":"
		out.RawString(prefix)
		out.Int64(int64(in.Impressions))
	}
	{
		const prefix string = ",\"clicks\":"
		out.RawString(prefix)
		out.Int64(int64(in.Clicks))
	}
	{
		const prefix string = ",\"ctr\":"
		out.RawString(prefix)
		out.Float64(float64(in.CTR))
	}
	{
		const prefix string = ",\"spend\":"
		out.RawString(prefix)
		out.Int64(int64(in.Spend))
	}
	{
		const prefix string = ",\"cpc\":"
		out.RawString(prefix)
		out.Float64(float64(in.CPC))
	}
	{
		const prefix string = ",\"partner_reward\":"
		out.RawString(prefix)
		out.Int64(int64(in.PartnerReward))
	}
	{
		const prefix string = ",\"platform_revenue\":"
		out.RawString(prefix)
		out.Int64(int64(in.PlatformRevenue))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v StatsEntityRow) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v StatsEntityRow) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *StatsEntityRow) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *StatsEntityRow) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto4(l, v)
}
func easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto5(in *jlexer.Lexer, out *PartnerIncomeStatsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "from":
			out.From = string(in.String())
		case "to":
			out.To = string(in.String())
		case "impressions":
			out.Impressions = int64(in.Int64())
		case "reward":
			out.Reward = int64(in.Int64())
		case "ecpm":
			out.ECPM = float64(in.Float64())
		case "rows":
			if in.IsNull() {
				in.Skip()
				out.Rows = nil
			} else {
				in.Delim('[')
				if out.Rows == nil {
					if !in.IsDelim(']') {
						out.Rows = make([]PartnerIncomeRowResponse, 0, 0)
					} else {
						out.Rows = []PartnerIncomeRowResponse{}
					}
				} else {
					out.Rows = (out.Rows)[:0]
				}
				for !in.IsDelim(']') {
					var v1 PartnerIncomeRowResponse
					(v1).UnmarshalEasyJSON(in)
					out.Rows = append(out.Rows, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto5(out *jwriter.Writer, in PartnerIncomeStatsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"from\":"
		out.RawString(prefix[1:])
		out.String(string(in.From))
	}
	{
		const prefix string = ",\"to\":"
		out.RawString(prefix)
		out.String(string(in.To))
	}
	{
		const prefix string = ",\"impressions\":"
		out.RawString(prefix)
		out.Int64(int64(in.Impressions))
	}
	{
		const prefix string = ",\"reward\":"
		out.RawString(prefix)
		out.Int64(int64(in.Reward))
	}
	{
		const prefix string = ",\"ecpm\":"
		out.RawString(prefix)
		out.Float64(float64(in.ECPM))
	}
	{
		const prefix string = ",\"rows\":"
		out.RawString(prefix)
		if in.Rows == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Rows {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartnerIncomeStatsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartnerIncomeStatsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartnerIncomeStatsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartnerIncomeStatsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto5(l, v)
}
func easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto6(in *jlexer.Lexer, out *PartnerIncomeRowResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "date":
			out.Date = string(in.String())
		case "site_id":
			out.SiteID = int(in.Int())
		case "site_name":
			out.SiteName = string(in.String())
		case "domain":
			out.Domain = string(in.String())
		case "block_id":
			out.BlockID = int(in.Int())
		case "block_name":
			out.BlockName = string(in.String())
		case "impressions":
			out.Impressions = int64(in.Int64())
		case "reward":
			out.Reward = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto6(out *jwriter.Writer, in PartnerIncomeRowResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"date\":"
		out.RawString(prefix[1:])
		out.String(string(in.Date))
	}
	{
		const prefix string = ",\"site_id\":"
		out.RawString(prefix)
		out.Int(int(in.SiteID))
	}
	{
		const prefix string = ",\"site_name\":"
		out.RawString(prefix)
		out.String(string(in.SiteName))
	}
	{
		const prefix string = ",\"domain\":"
		out.RawString(prefix)
		out.String(string(in.Domain))
	}
	{
		const prefix string = ",\"block_id\":"
		out.RawString(prefix)
		out.Int(int(in.BlockID))
	}
	{
		const prefix string = ",\"block_name\":"
		out.RawString(prefix)
		out.String(string(in.BlockName))
	}
	{
		const prefix string = ",\"impressions\":"
		out.RawString(prefix)
		out.Int64(int64(in.Impressions))
	}
	{
		const prefix string = ",\"reward\":"
		out.RawString(prefix)
		out.Int64(int64(in.Reward))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PartnerIncomeRowResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto6(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PartnerIncomeRowResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto6(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PartnerIncomeRowResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto6(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PartnerIncomeRowResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto6(l, v)
}
func easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto7(in *jlexer.Lexer, out *GroupStatsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "period":
			(out.Period).UnmarshalEasyJSON(in)
		case "totals":
			(out.Totals).UnmarshalEasyJSON(in)
		case "previous_totals":
			(out.PreviousTotals).UnmarshalEasyJSON(in)
		case "timeline":
			if in.IsNull() {
				in.Skip()
				out.Timeline = nil
			} else {
				in.Delim('[')
				if out.Timeline == nil {
					if !in.IsDelim(']') {
						out.Timeline = make([]StatsPoint, 0, 0)
					} else {
						out.Timeline = []StatsPoint{}
					}
				} else {
					out.Timeline = (out.Timeline)[:0]
				}
				for !in.IsDelim(']') {
					var v4 StatsPoint
					(v4).UnmarshalEasyJSON(in)
					out.Timeline = append(out.Timeline, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "ads":
			if in.IsNull() {
				in.Skip()
				out.Ads = nil
			} else {
				in.Delim('[')
				if out.Ads == nil {
					if !in.IsDelim(']') {
						out.Ads = make([]StatsEntityRow, 0, 0)
					} else {
						out.Ads = []StatsEntityRow{}
					}
				} else {
					out.Ads = (out.Ads)[:0]
				}
				for !in.IsDelim(']') {
					var v5 StatsEntityRow
					(v5).UnmarshalEasyJSON(in)
					out.Ads = append(out.Ads, v5)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "placements":
			if in.IsNull() {
				in.Skip()
				out.Placements = nil
			} else {
				in.Delim('[')
				if out.Placements == nil {
					if !in.IsDelim(']') {
						out.Placements = make([]StatsEntityRow, 0, 0)
					} else {
						out.Placements = []StatsEntityRow{}
					}
				} else {
					out.Placements = (out.Placements)[:0]
				}
				for !in.IsDelim(']') {
					var v6 StatsEntityRow
					(v6).UnmarshalEasyJSON(in)
					out.Placements = append(out.Placements, v6)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "unavailable_metrics":
			if in.IsNull() {
				in.Skip()
				out.UnavailableMetrics = nil
			} else {
				in.Delim('[')
				if out.UnavailableMetrics == nil {
					if !in.IsDelim(']') {
						out.UnavailableMetrics = make([]StatsUnavailableMetric, 0, 1)
					} else {
						out.UnavailableMetrics = []StatsUnavailableMetric{}
					}
				} else {
					out.UnavailableMetrics = (out.UnavailableMetrics)[:0]
				}
				for !in.IsDelim(']') {
					var v7 StatsUnavailableMetric
					(v7).UnmarshalEasyJSON(in)
					out.UnavailableMetrics = append(out.UnavailableMetrics, v7)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto7(out *jwriter.Writer, in GroupStatsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"period\":"
		out.RawString(prefix[1:])
		(in.Period).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"totals\":"
		out.RawString(prefix)
		(in.Totals).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"previous_totals\":"
		out.RawString(prefix)
		(in.PreviousTotals).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"timeline\":"
		out.RawString(prefix)
		if in.Timeline == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v8, v9 := range in.Timeline {
				if v8 > 0 {
					out.RawByte(',')
				}
				(v9).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"ads\":"
		out.RawString(prefix)
		if in.Ads == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v10, v11 := range in.Ads {
				if v10 > 0 {
					out.RawByte(',')
				}
				(v11).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"placements\":"
		out.RawString(prefix)
		if in.Placements == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v12, v13 := range in.Placements {
				if v12 > 0 {
					out.RawByte(',')
				}
				(v13).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"unavailable_metrics\":"
		out.RawString(prefix)
		if in.UnavailableMetrics == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v14, v15 := range in.UnavailableMetrics {
				if v14 > 0 {
					out.RawByte(',')
				}
				(v15).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v GroupStatsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto7(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v GroupStatsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto7(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *GroupStatsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto7(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *GroupStatsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto7(l, v)
}
func easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto8(in *jlexer.Lexer, out *CampaignStatsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "period":
			(out.Period).UnmarshalEasyJSON(in)
		case "totals":
			(out.Totals).UnmarshalEasyJSON(in)
		case "previous_totals":
			(out.PreviousTotals).UnmarshalEasyJSON(in)
		case "timeline":
			if in.IsNull() {
				in.Skip()
				out.Timeline = nil
			} else {
				in.Delim('[')
				if out.Timeline == nil {
					if !in.IsDelim(']') {
						out.Timeline = make([]StatsPoint, 0, 0)
					} else {
						out.Timeline = []StatsPoint{}
					}
				} else {
					out.Timeline = (out.Timeline)[:0]
				}
				for !in.IsDelim(']') {
					var v16 StatsPoint
					(v16).UnmarshalEasyJSON(in)
					out.Timeline = append(out.Timeline, v16)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "groups":
			if in.IsNull() {
				in.Skip()
				out.Groups = nil
			} else {
				in.Delim('[')
				if out.Groups == nil {
					if !in.IsDelim(']') {
						out.Groups = make([]StatsEntityRow, 0, 0)
					} else {
						out.Groups = []StatsEntityRow{}
					}
				} else {
					out.Groups = (out.Groups)[:0]
				}
				for !in.IsDelim(']') {
					var v17 StatsEntityRow
					(v17).UnmarshalEasyJSON(in)
					out.Groups = append(out.Groups, v17)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "placements":
			if in.IsNull() {
				in.Skip()
				out.Placements = nil
			} else {
				in.Delim('[')
				if out.Placements == nil {
					if !in.IsDelim(']') {
						out.Placements = make([]StatsEntityRow, 0, 0)
					} else {
						out.Placements = []StatsEntityRow{}
					}
				} else {
					out.Placements = (out.Placements)[:0]
				}
				for !in.IsDelim(']') {
					var v18 StatsEntityRow
					(v18).UnmarshalEasyJSON(in)
					out.Placements = append(out.Placements, v18)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "unavailable_metrics":
			if in.IsNull() {
				in.Skip()
				out.UnavailableMetrics = nil
			} else {
				in.Delim('[')
				if out.UnavailableMetrics == nil {
					if !in.IsDelim(']') {
						out.UnavailableMetrics = make([]StatsUnavailableMetric, 0, 1)
					} else {
						out.UnavailableMetrics = []StatsUnavailableMetric{}
					}
				} else {
					out.UnavailableMetrics = (out.UnavailableMetrics)[:0]
				}
				for !in.IsDelim(']') {
					var v19 StatsUnavailableMetric
					(v19).UnmarshalEasyJSON(in)
					out.UnavailableMetrics = append(out.UnavailableMetrics, v19)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto8(out *jwriter.Writer, in CampaignStatsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"period\":"
		out.RawString(prefix[1:])
		(in.Period).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"totals\":"
		out.RawString(prefix)
		(in.Totals).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"previous_totals\":"
		out.RawString(prefix)
		(in.PreviousTotals).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"timeline\":"
		out.RawString(prefix)
		if in.Timeline == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v20, v21 := range in.Timeline {
				if v20 > 0 {
					out.RawByte(',')
				}
				(v21).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"groups\":"
		out.RawString(prefix)
		if in.Groups == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v22, v23 := range in.Groups {
				if v22 > 0 {
					out.RawByte(',')
				}
				(v23).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"placements\":"
		out.RawString(prefix)
		if in.Placements == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v24, v25 := range in.Placements {
				if v24 > 0 {
					out.RawByte(',')
				}
				(v25).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"unavailable_metrics\":"
		out.RawString(prefix)
		if in.UnavailableMetrics == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v26, v27 := range in.UnavailableMetrics {
				if v26 > 0 {
					out.RawByte(',')
				}
				(v27).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v CampaignStatsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto8(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v CampaignStatsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto8(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *CampaignStatsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto8(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *CampaignStatsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto8(l, v)
}
func easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto9(in *jlexer.Lexer, out *AdStatsResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "period":
			(out.Period).UnmarshalEasyJSON(in)
		case "totals":
			(out.Totals).UnmarshalEasyJSON(in)
		case "previous_totals":
			(out.PreviousTotals).UnmarshalEasyJSON(in)
		case "timeline":
			if in.IsNull() {
				in.Skip()
				out.Timeline = nil
			} else {
				in.Delim('[')
				if out.Timeline == nil {
					if !in.IsDelim(']') {
						out.Timeline = make([]StatsPoint, 0, 0)
					} else {
						out.Timeline = []StatsPoint{}
					}
				} else {
					out.Timeline = (out.Timeline)[:0]
				}
				for !in.IsDelim(']') {
					var v28 StatsPoint
					(v28).UnmarshalEasyJSON(in)
					out.Timeline = append(out.Timeline, v28)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "placements":
			if in.IsNull() {
				in.Skip()
				out.Placements = nil
			} else {
				in.Delim('[')
				if out.Placements == nil {
					if !in.IsDelim(']') {
						out.Placements = make([]StatsEntityRow, 0, 0)
					} else {
						out.Placements = []StatsEntityRow{}
					}
				} else {
					out.Placements = (out.Placements)[:0]
				}
				for !in.IsDelim(']') {
					var v29 StatsEntityRow
					(v29).UnmarshalEasyJSON(in)
					out.Placements = append(out.Placements, v29)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "unavailable_metrics":
			if in.IsNull() {
				in.Skip()
				out.UnavailableMetrics = nil
			} else {
				in.Delim('[')
				if out.UnavailableMetrics == nil {
					if !in.IsDelim(']') {
						out.UnavailableMetrics = make([]StatsUnavailableMetric, 0, 1)
					} else {
						out.UnavailableMetrics = []StatsUnavailableMetric{}
					}
				} else {
					out.UnavailableMetrics = (out.UnavailableMetrics)[:0]
				}
				for !in.IsDelim(']') {
					var v30 StatsUnavailableMetric
					(v30).UnmarshalEasyJSON(in)
					out.UnavailableMetrics = append(out.UnavailableMetrics, v30)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto9(out *jwriter.Writer, in AdStatsResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"period\":"
		out.RawString(prefix[1:])
		(in.Period).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"totals\":"
		out.RawString(prefix)
		(in.Totals).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"previous_totals\":"
		out.RawString(prefix)
		(in.PreviousTotals).MarshalEasyJSON(out)
	}
	{
		const prefix string = ",\"timeline\":"
		out.RawString(prefix)
		if in.Timeline == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v31, v32 := range in.Timeline {
				if v31 > 0 {
					out.RawByte(',')
				}
				(v32).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"placements\":"
		out.RawString(prefix)
		if in.Placements == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v33, v34 := range in.Placements {
				if v33 > 0 {
					out.RawByte(',')
				}
				(v34).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"unavailable_metrics\":"
		out.RawString(prefix)
		if in.UnavailableMetrics == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v35, v36 := range in.UnavailableMetrics {
				if v35 > 0 {
					out.RawByte(',')
				}
				(v36).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AdStatsResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto9(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AdStatsResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonE3ab7953EncodeEshkereInternalHandlerV1Dto9(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AdStatsResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto9(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AdStatsResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonE3ab7953DecodeEshkereInternalHandlerV1Dto9(l, v)
}
